# init_db_v11.py — v11 (Render + PostgreSQL)
# - Idempotent schema creation & optional admin seeding
# - SQLAlchemy (psycopg v3 dialect)
# - Reads DATABASE_URL and optional ADMIN_* from environment
# - Best used for fresh/dev database creation (e.g. ascenda_dev)

import os
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError

from dotenv import load_dotenv
load_dotenv()

# ---------------- Password hashing (for admin/demo users) ----------------
try:
    from passlib.hash import pbkdf2_sha256
except Exception as e:
    raise SystemExit(
        "passlib is not installed. Add `passlib>=1.7` to requirements.txt.\n"
        f"Underlying error: {e}"
    )


# ---------------- Resolve database URL ----------------
def _env(key: str, default: str | None = None) -> str | None:
    val = os.environ.get(key, default)
    return val if (val is not None and str(val).strip() != "") else default


def _normalize_db_url(url: str) -> str:
    if url.startswith("postgres://"):
        url = url.replace("postgres://", "postgresql://", 1)
    if url.startswith("postgresql://"):
        url = url.replace("postgresql://", "postgresql+psycopg://", 1)

    app_env = os.environ.get("APP_ENV", "development").lower()

    if "sslmode=" not in url:
        sep = "&" if "?" in url else "?"
        if app_env == "production":
            url = f"{url}{sep}sslmode=require"
        else:
            url = f"{url}{sep}sslmode=disable"
    return url


def _compose_db_url_from_parts() -> str:
    from urllib.parse import quote_plus

    host = _env("DB_HOST")
    port = _env("DB_PORT", "5432")
    name = _env("DB_NAME", "postgres")
    user = _env("DB_USER", "postgres")
    pwd = _env("DB_PASSWORD")
    sslmode = _env("DB_SSLMODE", "require")

    if not (host and pwd):
        raise RuntimeError(
            "DATABASE_URL is not set and DB_HOST/DB_PASSWORD are missing. "
            "Set DATABASE_URL or DB_* environment variables."
        )

    enc_pwd = quote_plus(pwd)
    return f"postgresql+psycopg://{user}:{enc_pwd}@{host}:{port}/{name}?sslmode={sslmode}"


db_url = _env("DATABASE_URL")
if db_url:
    db_url = _normalize_db_url(db_url)
else:
    db_url = _compose_db_url_from_parts()


def _mask(url: str) -> str:
    try:
        head, tail = url.split("://", 1)
        creds, rest = tail.split("@", 1)
        user = creds.split(":", 1)[0]
        return f"{head}://{user}:***@{rest}"
    except Exception:
        return "postgresql+psycopg://***"


print("Connecting to:", _mask(db_url))

engine = create_engine(db_url, pool_pre_ping=True, future=True)


# ================== SCHEMA (PostgreSQL) ==================
SCHEMA_SQL = """
CREATE EXTENSION IF NOT EXISTS citext;

-- --------------------------------------------------------
-- Enum types
-- --------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'asc_change_impact' AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.asc_change_impact AS ENUM ('MINOR', 'KPI');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'asc_change_source' AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.asc_change_source AS ENUM ('REQUEST', 'FORCE');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'asc_request_status' AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.asc_request_status AS ENUM (
            'IN_REVIEW',
            'APPROVED',
            'REJECTED',
            'CANCELLED',
            'WITHDRAWN',
            'DELETED'
        );
    END IF;
END $$;

-- --------------------------------------------------------
-- Core lookups
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS business_units (
    business_unit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS objectives (
    objective_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT TRUE,
    category TEXT
);

CREATE TABLE IF NOT EXISTS business_lines (
    business_line_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_unit_id INTEGER NOT NULL REFERENCES business_units(business_unit_id),
    name TEXT NOT NULL,
    supplier TEXT,
    category TEXT,
    product_group TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    UNIQUE (business_unit_id, name)
);

CREATE TABLE IF NOT EXISTS customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name TEXT NOT NULL,
    sector TEXT,
    region TEXT,
    city TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    latitude NUMERIC,
    longitude NUMERIC,
    party_id VARCHAR(20),
    account_id VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS target_audiences (
    audience_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(customer_id),
    title TEXT,
    name TEXT NOT NULL,
    department TEXT,
    position TEXT,
    potentiality TEXT,
    loyalty TEXT,
    mobile TEXT,
    landline TEXT,
    external_number TEXT,
    email TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS items (
    product_id TEXT PRIMARY KEY,
    article_number TEXT UNIQUE,
    description TEXT,
    business_line_id INTEGER NOT NULL REFERENCES business_lines(business_line_id),
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email CITEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT,
    region TEXT,
    business_unit_id INTEGER REFERENCES business_units(business_unit_id),
    role TEXT NOT NULL CHECK (
        role IN (
            'admin',
            'rep',
            'maintenance',
            'supervisor',
            'sales manager',
            'biomedical manager'
        )
    ),
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS role_objectives (
    role TEXT NOT NULL CHECK (
        role IN (
            'admin',
            'rep',
            'maintenance',
            'supervisor',
            'sales manager',
            'biomedical manager'
        )
    ),
    objective_id INTEGER NOT NULL REFERENCES objectives(objective_id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (role, objective_id)
);

-- --------------------------------------------------------
-- Project module
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS project_objectives (
    project_objective_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS projects (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    assigned_by_id BIGINT NOT NULL REFERENCES users(user_id),
    assigned_to_id BIGINT NOT NULL REFERENCES users(user_id),
    business_line_id BIGINT NOT NULL REFERENCES business_lines(business_line_id),
    product_id TEXT REFERENCES items(product_id),
    customer_id BIGINT NOT NULL REFERENCES customers(customer_id),
    planned_start_date DATE NOT NULL,
    planned_end_date DATE NOT NULL,
    actual_end_date DATE,
    status TEXT NOT NULL,
    project_objective_id BIGINT NOT NULL REFERENCES project_objectives(project_objective_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_change_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id),
    changed_by_id BIGINT NOT NULL REFERENCES users(user_id),
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS project_change_details (
    detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES project_change_events(event_id) ON DELETE CASCADE,
    field_name TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT
);

-- --------------------------------------------------------
-- Visits module
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS visits (
    visit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    submitted_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    accuracy_m DOUBLE PRECISION,
    customer_id INTEGER NOT NULL REFERENCES customers(customer_id),
    audience_id INTEGER REFERENCES target_audiences(audience_id),
    business_line_id INTEGER REFERENCES business_lines(business_line_id),
    product_id TEXT REFERENCES items(product_id),
    objective_id INTEGER NOT NULL REFERENCES objectives(objective_id),
    notes TEXT,
    evaluation TEXT CHECK (
        evaluation IS NULL OR evaluation IN ('Positive', 'Negative', 'Neutral')
    ),
    submitted_at_local TIMESTAMP,
    project_id BIGINT REFERENCES projects(project_id),
    other_audience_name TEXT,
    other_audience_department TEXT,
    other_audience_position TEXT,
    other_audience_title TEXT,
    other_audience_phone TEXT,
    other_audience_email TEXT,
    other_customer_name TEXT,
    is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    deleted_by  INTEGER REFERENCES users(user_id),
    version     INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS home_visits (
    home_visit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id INTEGER NOT NULL UNIQUE REFERENCES visits(visit_id) ON DELETE CASCADE,
    patient_name TEXT NOT NULL,
    patient_phone TEXT NOT NULL,
    serial_no TEXT NOT NULL UNIQUE,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shelf_movement_headers (
    movement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id INTEGER NOT NULL UNIQUE REFERENCES visits(visit_id) ON DELETE CASCADE,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shelf_movement_lines (
    line_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_id INTEGER NOT NULL REFERENCES shelf_movement_headers(movement_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES items(product_id),
    qty_checked DOUBLE PRECISION NOT NULL
);

-- --------------------------------------------------------
-- Visit change requests
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS request_changes (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id BIGINT NOT NULL REFERENCES visits(visit_id) ON DELETE CASCADE,
    change_source public.asc_change_source NOT NULL DEFAULT 'REQUEST',
    requested_by BIGINT NOT NULL REFERENCES users(user_id),
    request_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status public.asc_request_status NOT NULL DEFAULT 'IN_REVIEW',
    changed_by BIGINT REFERENCES users(user_id),
    resolve_date TIMESTAMPTZ,
    request_note TEXT NOT NULL,
    reject_note TEXT,
    applied_at TIMESTAMPTZ,
    apply_error TEXT
);

CREATE TABLE IF NOT EXISTS request_change_details (
    detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES request_changes(request_id) ON DELETE CASCADE,
    field TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT
);

-- --------------------------------------------------------
-- Login rate limiting
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS login_attempts (
    username        CITEXT PRIMARY KEY,
    attempt_count   INTEGER NOT NULL DEFAULT 0,
    locked_until    TIMESTAMPTZ,
    last_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------
-- Sessions / auth telemetry
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_sessions (
    session_id TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at_utc TIMESTAMPTZ NOT NULL,
    revoked_at_utc TIMESTAMPTZ,
    closed_reason TEXT,
    last_seen_utc TIMESTAMPTZ,
    ip INET,
    user_agent TEXT
);

CREATE TABLE IF NOT EXISTS app_session_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES app_sessions(session_id) ON DELETE CASCADE,
    at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    event_type TEXT NOT NULL,
    ip INET,
    user_agent TEXT,
    details JSONB DEFAULT '{}'::jsonb
);

-- --------------------------------------------------------
-- Target Management Module
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_categories (
    product_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_unit_id    INTEGER NOT NULL REFERENCES business_units(business_unit_id),
    name                TEXT    NOT NULL,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (business_unit_id, name)
);

ALTER TABLE business_lines
    ADD COLUMN IF NOT EXISTS product_category_id INTEGER
    REFERENCES product_categories(product_category_id);

CREATE TABLE IF NOT EXISTS target_year (
    year           INTEGER       PRIMARY KEY,
    budget_amount  NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (budget_amount >= 0),
    budget_visits  INTEGER       NOT NULL DEFAULT 0 CHECK (budget_visits >= 0),
    status         TEXT          NOT NULL DEFAULT 'DRAFT'
                   CHECK (status IN ('DRAFT', 'ACTIVE', 'LOCKED')),
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by     INTEGER       REFERENCES users(user_id),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_by     INTEGER       REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS target_rep (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year       INTEGER     NOT NULL REFERENCES target_year(year) ON DELETE CASCADE,
    user_id    INTEGER     NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by INTEGER     REFERENCES users(user_id),
    UNIQUE (year, user_id)
);

CREATE TABLE IF NOT EXISTS target_breakdown (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_rep_id       BIGINT        NOT NULL REFERENCES target_rep(id) ON DELETE CASCADE,
    year                INTEGER       NOT NULL,
    user_id             INTEGER       NOT NULL,
    breakdown_level     TEXT          NOT NULL
                        CHECK (breakdown_level IN (
                            'customer','business_unit',
                            'product_category','business_line','article'
                        )),
    customer_id         INTEGER       REFERENCES customers(customer_id),
    business_unit_id    INTEGER       REFERENCES business_units(business_unit_id),
    product_category_id INTEGER       REFERENCES product_categories(product_category_id),
    business_line_id    INTEGER       REFERENCES business_lines(business_line_id),
    article_id          TEXT          REFERENCES items(product_id),
    target_amount       NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (target_amount >= 0),
    target_visits       INTEGER       NOT NULL DEFAULT 0 CHECK (target_visits >= 0),
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by          INTEGER       REFERENCES users(user_id),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_by          INTEGER       REFERENCES users(user_id)
);

-- --------------------------------------------------------
-- Indexes
-- --------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

CREATE INDEX IF NOT EXISTS idx_business_lines_bu ON business_lines(business_unit_id);
CREATE INDEX IF NOT EXISTS idx_business_lines_bu_name ON business_lines(business_unit_id, name);

CREATE INDEX IF NOT EXISTS idx_customers_account_name ON customers(account_name);

CREATE INDEX IF NOT EXISTS idx_items_line ON items(business_line_id);
CREATE INDEX IF NOT EXISTS idx_items_article ON items(article_number);

CREATE INDEX IF NOT EXISTS idx_objectives_name ON objectives(name);
CREATE INDEX IF NOT EXISTS idx_objectives_active ON objectives(is_active);

CREATE INDEX IF NOT EXISTS idx_home_visits_serial ON home_visits(serial_no);
CREATE INDEX IF NOT EXISTS idx_home_visits_phone ON home_visits(patient_phone);

CREATE INDEX IF NOT EXISTS idx_projects_business_line ON projects(business_line_id);
CREATE INDEX IF NOT EXISTS idx_projects_customer ON projects(customer_id);
CREATE INDEX IF NOT EXISTS idx_projects_rep_active
    ON projects(assigned_to_id)
    WHERE status IN ('Not Started', 'Open');

CREATE INDEX IF NOT EXISTS idx_pce_project_id ON project_change_events(project_id);
CREATE INDEX IF NOT EXISTS idx_pcd_event_id ON project_change_details(event_id);

CREATE INDEX IF NOT EXISTS idx_role_objectives_role ON role_objectives(role);
CREATE INDEX IF NOT EXISTS idx_role_objectives_objective ON role_objectives(objective_id);

CREATE INDEX IF NOT EXISTS idx_visits_user ON visits(user_id, submitted_at_utc);
CREATE INDEX IF NOT EXISTS idx_visits_customer ON visits(customer_id);
CREATE INDEX IF NOT EXISTS idx_visits_audience ON visits(audience_id);
CREATE INDEX IF NOT EXISTS idx_visits_business_line ON visits(business_line_id);
CREATE INDEX IF NOT EXISTS idx_visits_product ON visits(product_id);
CREATE INDEX IF NOT EXISTS idx_visits_project_id ON visits(project_id);

CREATE INDEX IF NOT EXISTS idx_smv_hdr_visit ON shelf_movement_headers(visit_id);
CREATE INDEX IF NOT EXISTS idx_smv_lines_movement ON shelf_movement_lines(movement_id);
CREATE INDEX IF NOT EXISTS idx_smv_lines_product ON shelf_movement_lines(product_id);

CREATE INDEX IF NOT EXISTS idx_req_changes_visit ON request_changes(visit_id);
CREATE INDEX IF NOT EXISTS idx_req_changes_requested_by ON request_changes(requested_by);
CREATE INDEX IF NOT EXISTS idx_req_changes_status_date ON request_changes(status, request_date DESC);
CREATE INDEX IF NOT EXISTS idx_req_change_details_request ON request_change_details(request_id);
CREATE INDEX IF NOT EXISTS idx_req_change_details_field ON request_change_details(field);

CREATE UNIQUE INDEX IF NOT EXISTS uq_one_open_request_per_visit
    ON request_changes(visit_id)
    WHERE status = 'IN_REVIEW'::public.asc_request_status;

CREATE UNIQUE INDEX IF NOT EXISTS uq_target_audience_customer_name_dept_pos_ci
    ON target_audiences (
        customer_id,
        lower(COALESCE(name, '')),
        lower(COALESCE(department, '')),
        lower(COALESCE(position, ''))
    );

ALTER TABLE visits ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS ix_app_sessions_active
    ON app_sessions(expires_at_utc)
    WHERE revoked_at_utc IS NULL;

CREATE INDEX IF NOT EXISTS ix_app_session_events_session
    ON app_session_events(session_id);

CREATE INDEX IF NOT EXISTS idx_product_categories_bu ON product_categories(business_unit_id);
CREATE INDEX IF NOT EXISTS idx_business_lines_cat    ON business_lines(product_category_id);
CREATE INDEX IF NOT EXISTS idx_target_rep_year       ON target_rep(year);
CREATE INDEX IF NOT EXISTS idx_target_rep_user       ON target_rep(user_id);
CREATE INDEX IF NOT EXISTS idx_target_bd_rep         ON target_breakdown(target_rep_id);
CREATE INDEX IF NOT EXISTS idx_target_bd_year_user   ON target_breakdown(year, user_id);
CREATE INDEX IF NOT EXISTS idx_target_bd_customer    ON target_breakdown(customer_id);
CREATE INDEX IF NOT EXISTS idx_target_bd_bu          ON target_breakdown(business_unit_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_target_breakdown
    ON target_breakdown (
        target_rep_id,
        COALESCE(customer_id,          -1),
        COALESCE(business_unit_id,     -1),
        COALESCE(product_category_id,  -1),
        COALESCE(business_line_id,     -1),
        COALESCE(article_id,           '')
    );
"""


def ensure_schema_and_seed():
    with engine.begin() as conn:
        conn.exec_driver_sql(SCHEMA_SQL)

        admin_email = (_env("ADMIN_EMAIL", "") or "").strip().lower()
        admin_password = (_env("ADMIN_PASSWORD", "") or "").strip()

        if admin_email and admin_password:
            exists = conn.execute(
                text("SELECT 1 FROM users WHERE email = :e"),
                {"e": admin_email},
            ).fetchone()

            if not exists:
                conn.execute(
                    text(
                        """
                        INSERT INTO users (
                            email,
                            password_hash,
                            name,
                            region,
                            business_unit_id,
                            role,
                            is_active
                        )
                        VALUES (
                            :email,
                            :pwd,
                            :name,
                            :region,
                            NULL,
                            'admin',
                            TRUE
                        )
                        """
                    ),
                    {
                        "email": admin_email,
                        "pwd": pbkdf2_sha256.hash(admin_password),
                        "name": "Administrator",
                        "region": "HQ",
                    },
                )
                print(f"✅ Created initial admin: {admin_email}")

    print("✅ Schema ensured & base data ready.")


if __name__ == "__main__":
    try:
        ensure_schema_and_seed()
    except SQLAlchemyError as e:
        raise SystemExit(f"DB error: {e}")