# init_db_v11.py — v11 (Render + PostgreSQL)
# - Idempotent schema creation & seeding
# - SQLAlchemy (psycopg v3 dialect)
# - Reads DATABASE_URL and optional ADMIN_* from environment
# - Safe to run at every deploy

import os
from urllib.parse import quote_plus
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError

# ---------------- Password hashing (for admin/demo users) ----------------
try:
    from passlib.hash import pbkdf2_sha256
except Exception as e:
    raise SystemExit(
        "passlib is not installed. Add `passlib>=1.7` to requirements.txt.\n"
        f"Underlying error: {e}"
    )

# ---------------- Resolve database URL ----------------
def _env(key: str, default: str | None = None) -> str | None:
    """Lightweight env reader."""
    val = os.environ.get(key, default)
    return val if (val is not None and str(val).strip() != "") else default

def _normalize_db_url(url: str) -> str:
    if url.startswith("postgres://"):
        url = url.replace("postgres://", "postgresql://", 1)
    if url.startswith("postgresql://"):
        url = url.replace("postgresql://", "postgresql+psycopg://", 1)
    if "sslmode=" not in url:
        sep = "&" if "?" in url else "?"
        url = f"{url}{sep}sslmode=require"
    return url

def _compose_db_url_from_parts() -> str:
    host = _env("DB_HOST")
    port = _env("DB_PORT", "5432")
    name = _env("DB_NAME", "postgres")
    user = _env("DB_USER", "postgres")
    pwd  = _env("DB_PASSWORD")
    if not (host and pwd):
        raise RuntimeError(
            "DATABASE_URL is not set and DB_HOST/DB_PASSWORD are missing. "
            "Set DATABASE_URL in Render → Environment."
        )
    from urllib.parse import quote_plus
    enc_pwd = quote_plus(pwd)
    return f"postgresql+psycopg://{user}:{enc_pwd}@{host}:{port}/{name}?sslmode=require"

db_url = _env("DATABASE_URL")
if db_url:
    db_url = _normalize_db_url(db_url)
else:
    db_url = _compose_db_url_from_parts()

def _mask(url: str) -> str:
    try:
        head, tail = url.split("://", 1)
        creds, rest = tail.split("@", 1)
        user = creds.split(":", 1)[0]
        return f"{head}://{user}:***@{rest}"
    except Exception:
        return "postgresql+psycopg://***"

print("Connecting to:", _mask(db_url))

engine = create_engine(db_url, pool_pre_ping=True, future=True)

# ================== SCHEMA (PostgreSQL) ==================
SCHEMA_SQL = """
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS business_units (
  business_unit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS objectives (
  objective_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS business_lines (
  business_line_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_unit_id INTEGER NOT NULL REFERENCES business_units(business_unit_id),
  name TEXT NOT NULL,
  supplier TEXT,
  category TEXT,
  product_group TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  UNIQUE (business_unit_id, name)
);

CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email CITEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT,
  region TEXT,
  business_unit_id INTEGER REFERENCES business_units(business_unit_id),
  role TEXT NOT NULL CHECK (role IN ('admin','rep')),
  is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS customers (
  customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_name TEXT NOT NULL,
  sector TEXT,
  region TEXT,
  city TEXT,
  is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS target_audiences (
  audience_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(customer_id),
  title TEXT,
  name TEXT NOT NULL,
  department TEXT,
  position TEXT,
  potentiality TEXT,
  loyalty TEXT,
  mobile TEXT,
  landline TEXT,
  external_number TEXT,
  email TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  UNIQUE (customer_id, name)
);

CREATE TABLE IF NOT EXISTS items (
  product_id TEXT PRIMARY KEY,
  article_number TEXT UNIQUE,
  description TEXT,
  business_line_id INTEGER NOT NULL REFERENCES business_lines(business_line_id),
  is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS visits (
  visit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id),
  submitted_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  submitted_at_local TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  accuracy_m DOUBLE PRECISION,
  customer_id INTEGER NOT NULL REFERENCES customers(customer_id),
  audience_id INTEGER REFERENCES target_audiences(audience_id),
  business_line_id INTEGER NOT NULL REFERENCES business_lines(business_line_id),
  product_id TEXT REFERENCES items(product_id),
  objective_id INTEGER NOT NULL REFERENCES objectives(objective_id),
  notes TEXT,
  evaluation TEXT NOT NULL CHECK (evaluation IN ('Positive','Negative','Neutral','IDK'))
);

CREATE TABLE IF NOT EXISTS home_visits (
  home_visit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id INTEGER NOT NULL UNIQUE REFERENCES visits(visit_id) ON DELETE CASCADE,
  patient_name TEXT NOT NULL,
  patient_phone TEXT NOT NULL,
  serial_no TEXT UNIQUE NOT NULL,
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shelf_movement_headers (
  movement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id INTEGER NOT NULL UNIQUE REFERENCES visits(visit_id) ON DELETE CASCADE,
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shelf_movement_lines (
  line_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movement_id INTEGER NOT NULL REFERENCES shelf_movement_headers(movement_id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES items(product_id),
  qty_checked DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS app_sessions (
  session_id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at_utc TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_customers_account_name ON customers(account_name);
CREATE INDEX IF NOT EXISTS idx_objectives_name ON objectives(name);
CREATE INDEX IF NOT EXISTS idx_objectives_active ON objectives(is_active);

CREATE INDEX IF NOT EXISTS idx_visits_user ON visits(user_id, submitted_at_utc);
CREATE INDEX IF NOT EXISTS idx_visits_customer ON visits(customer_id);
CREATE INDEX IF NOT EXISTS idx_visits_audience ON visits(audience_id);
CREATE INDEX IF NOT EXISTS idx_visits_business_line ON visits(business_line_id);
CREATE INDEX IF NOT EXISTS idx_visits_product ON visits(product_id);

CREATE INDEX IF NOT EXISTS idx_business_lines_bu ON business_lines(business_unit_id);
CREATE INDEX IF NOT EXISTS idx_business_lines_bu_name ON business_lines(business_unit_id, name);
CREATE INDEX IF NOT EXISTS idx_items_line ON items(business_line_id);
CREATE INDEX IF NOT EXISTS idx_items_article ON items(article_number);

CREATE INDEX IF NOT EXISTS idx_home_visits_serial ON home_visits(serial_no);
CREATE INDEX IF NOT EXISTS idx_home_visits_phone ON home_visits(patient_phone);

CREATE INDEX IF NOT EXISTS idx_smv_hdr_visit ON shelf_movement_headers(visit_id);
CREATE INDEX IF NOT EXISTS idx_smv_lines_movement ON shelf_movement_lines(movement_id);
CREATE INDEX IF NOT EXISTS idx_smv_lines_product ON shelf_movement_lines(product_id);
"""

SEED_BUSINESS_UNITS = [
    ("ANESTHESIA & ICU", True),
    ("GASTROINTESTINAL & OR", True),
    ("RESPIRATORY CARE", True),
    ("PHARMA & MEDICAL SHOWROOMS", True),
    ("OTHERS", True),
]

SEED_OBJECTIVES = [
    ("01. Profiling",), ("02. Standard F2F Call",), ("03. Sample Delivery",),
    ("04. Demonstration/AV",), ("05. Presentation/AV",), ("06. Workshop/AV",),
    ("07. Evaluation Follow Up",), ("08. Handling Objection",),
    ("09. Quotation Follow Up",), ("10. Post-Sales Technical Feedback",),
    ("11. Post-Sales Logistic Feedback",), ("12. Monitoring Competitors",),
    ("13. Trouble Shooting",), ("14. Delivery Follow Up",),
    ("15. Collection Follow Up",), ("16. Shelf Movement",)
]

#
DEMO_REPS = [
    ("ahmed.rep@company.com", "Ahmed Ali", "C/R"),
    ("sara.rep@company.com", "Sara Nasser", "W/R"),
]

def ensure_schema_and_seed():
    with engine.begin() as conn:
        conn.exec_driver_sql(SCHEMA_SQL)

        conn.execute(
            text("""
            INSERT INTO business_units (name, is_active)
            VALUES (:name, :active)
            ON CONFLICT (name) DO NOTHING
            """),
            [{"name": n, "active": a} for (n, a) in SEED_BUSINESS_UNITS]
        )

        conn.execute(
            text("""
            INSERT INTO objectives (name)
            VALUES (:name)
            ON CONFLICT (name) DO NOTHING
            """),
            [{"name": n[0]} for n in SEED_OBJECTIVES]
        )

        admin_email = (_env("ADMIN_EMAIL", "") or "").strip().lower()
        admin_password = (_env("ADMIN_PASSWORD", "") or "").strip()
        if admin_email and admin_password:
            exists = conn.execute(
                text("SELECT 1 FROM users WHERE email=:e"),
                {"e": admin_email}
            ).fetchone()
            if not exists:
                conn.execute(
                    text("""
                        INSERT INTO users(email, password_hash, name, region, business_unit_id, role, is_active)
                        VALUES (:email, :pwd, :name, :region, NULL, 'admin', TRUE)
                    """),
                    {
                        "email": admin_email,
                        "pwd": pbkdf2_sha256.hash(admin_password),
                        "name": "Administrator",
                        "region": "HQ",
                    },
                )
                print(f"✅ Created initial admin: {admin_email}")

        if (_env("SEED_DEMO", "0") or "0").strip() == "1":
            for email, name, region in DEMO_REPS:
                r = conn.execute(text("SELECT 1 FROM users WHERE email=:e"), {"e": email}).fetchone()
                if not r:
                    conn.execute(
                        text("""
                            INSERT INTO users(email, password_hash, name, region, business_unit_id, role, is_active)
                            VALUES (:email, :pwd, :name, :region, NULL, 'rep', TRUE)
                        """),
                        {"email": email, "pwd": pbkdf2_sha256.hash("rep12345"), "name": name, "region": region},
                    )
            print("✅ Seeded demo reps.")

    print("✅ Schema ensured & base data ready.")

if __name__ == "__main__":
    try:
        ensure_schema_and_seed()
    except SQLAlchemyError as e:
        raise SystemExit(f"DB error: {e}")
