-- migrations/notifications_schema.sql
-- Idempotent — safe to re-run on every app startup.

CREATE TABLE IF NOT EXISTS notifications (
    notification_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id INTEGER NOT NULL REFERENCES users(user_id),
    actor_user_id     INTEGER REFERENCES users(user_id),
    category          TEXT NOT NULL,
    event_type        TEXT NOT NULL,
    title             TEXT NOT NULL,
    body              TEXT,
    link_page         TEXT,
    link_params       JSONB,
    is_read           BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    read_at           TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient
    ON notifications (recipient_user_id, is_read, created_at DESC);
