-- migrations/quotations_schema.sql
-- Idempotent — safe to re-run on every app startup.

CREATE TABLE IF NOT EXISTS quotation_requests (
    quotation_id      BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_number  TEXT    NOT NULL UNIQUE,
    customer_id       INTEGER NOT NULL REFERENCES customers(customer_id),
    rep_user_id       INTEGER NOT NULL REFERENCES users(user_id),
    quotation_date    DATE    NOT NULL DEFAULT CURRENT_DATE,
    vat_rate          NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (vat_rate BETWEEN 0 AND 100),

    remarks           TEXT,
    validity_days     INTEGER CHECK (validity_days IN (30, 60, 90, 180, 365)) NOT NULL,
    delivery_terms    TEXT CHECK (delivery_terms IN (
                           'Immediate', '15 Days', '30 Days', '45 Days',
                           '60 Days', '90 Days', '120 Days'
                       )) NOT NULL,
    payment_terms     TEXT CHECK (payment_terms IN (
                           'Cash in Advance', 'Cash on Delivery', '15 Days', '30 Days',
                           '60 Days', '90 Days', '120 Days', 'As per Agreed Policy'
                       )) NOT NULL,

    status    TEXT NOT NULL DEFAULT 'IN_REVIEW' CHECK (status IN (
                   'IN_REVIEW', 'EDIT_REQUESTED', 'REJECTED', 'APPROVED', 'DONE', 'WITHDRAWN'
               )),
    version   INTEGER NOT NULL DEFAULT 0,

    submitted_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    submitted_by  INTEGER NOT NULL REFERENCES users(user_id),

    manager_user_id     INTEGER REFERENCES users(user_id),
    manager_decided_at  TIMESTAMPTZ,
    manager_comment     TEXT,

    coordinator_user_id  INTEGER REFERENCES users(user_id),
    coordinator_done_at  TIMESTAMPTZ,
    coordinator_note     TEXT,
    odoo_reference        TEXT,

    withdrawn_at       TIMESTAMPTZ,
    withdrawn_by        INTEGER REFERENCES users(user_id),
    withdrawal_reason    TEXT,

    is_deleted   BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMPTZ,
    deleted_by     INTEGER REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS quotation_lines (
    line_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id  BIGINT NOT NULL REFERENCES quotation_requests(quotation_id) ON DELETE CASCADE,
    line_no       SMALLINT NOT NULL CHECK (line_no >= 1),
    product_id    TEXT NOT NULL REFERENCES items(product_id),
    quantity      INTEGER NOT NULL CHECK (quantity > 0),
    unit_price    NUMERIC(14,2) NOT NULL CHECK (unit_price >= 0),
    discount_pct  NUMERIC(5,2)  NOT NULL DEFAULT 0 CHECK (discount_pct BETWEEN 0 AND 100),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (quotation_id, line_no),
    UNIQUE (quotation_id, product_id)
);

CREATE TABLE IF NOT EXISTS quotation_revisions (
    revision_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id    BIGINT NOT NULL REFERENCES quotation_requests(quotation_id) ON DELETE CASCADE,
    revision_no     SMALLINT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      INTEGER NOT NULL REFERENCES users(user_id),

    customer_id     INTEGER NOT NULL REFERENCES customers(customer_id),
    quotation_date  DATE NOT NULL,
    vat_rate        NUMERIC(5,2) NOT NULL,
    remarks         TEXT,
    validity_days   INTEGER NOT NULL,
    delivery_terms  TEXT NOT NULL,
    payment_terms   TEXT NOT NULL,

    subtotal        NUMERIC(16,2) NOT NULL,
    vat_amount      NUMERIC(16,2) NOT NULL,
    grand_total     NUMERIC(16,2) NOT NULL,

    UNIQUE (quotation_id, revision_no)
);

CREATE TABLE IF NOT EXISTS quotation_revision_lines (
    revision_line_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id              BIGINT NOT NULL REFERENCES quotation_revisions(revision_id) ON DELETE CASCADE,
    line_no                  SMALLINT NOT NULL,
    product_id               TEXT NOT NULL REFERENCES items(product_id),
    article_number_snapshot  TEXT,
    description_snapshot     TEXT,
    quantity                 INTEGER NOT NULL,
    unit_price                NUMERIC(14,2) NOT NULL,
    discount_pct               NUMERIC(5,2) NOT NULL,
    line_total                  NUMERIC(16,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS quotation_status_events (
    event_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id    BIGINT NOT NULL REFERENCES quotation_requests(quotation_id) ON DELETE CASCADE,
    event_type      TEXT NOT NULL CHECK (event_type IN (
                         'SUBMITTED', 'RESUBMITTED', 'EDIT_REQUESTED', 'APPROVED',
                         'REJECTED', 'WITHDRAWN', 'RETURNED_FOR_REVISION', 'MARKED_DONE'
                     )),
    actor_user_id   INTEGER NOT NULL REFERENCES users(user_id),
    from_status     TEXT,
    to_status       TEXT NOT NULL,
    comment         TEXT,
    revision_id     BIGINT REFERENCES quotation_revisions(revision_id),
    at_utc          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quotation_number_counters (
    year     INTEGER PRIMARY KEY,
    last_seq INTEGER NOT NULL DEFAULT 0
);

-- ── Indexes ───────────────────────────────────────────────────────────────────
CREATE UNIQUE INDEX IF NOT EXISTS idx_qr_odoo_ref_unique
    ON quotation_requests (odoo_reference) WHERE odoo_reference IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_qr_status          ON quotation_requests(status);
CREATE INDEX IF NOT EXISTS idx_qr_rep              ON quotation_requests(rep_user_id);
CREATE INDEX IF NOT EXISTS idx_qr_customer         ON quotation_requests(customer_id);
CREATE INDEX IF NOT EXISTS idx_qr_manager          ON quotation_requests(manager_user_id);
CREATE INDEX IF NOT EXISTS idx_qr_coordinator      ON quotation_requests(coordinator_user_id);
CREATE INDEX IF NOT EXISTS idx_ql_quotation        ON quotation_lines(quotation_id);
CREATE INDEX IF NOT EXISTS idx_ql_product          ON quotation_lines(product_id);
CREATE INDEX IF NOT EXISTS idx_qrev_quotation      ON quotation_revisions(quotation_id, revision_no);
CREATE INDEX IF NOT EXISTS idx_qse_quotation       ON quotation_status_events(quotation_id, at_utc);

-- ── users.role CHECK migration — add 'sales coordinator' ────────────────────────
DO $$
DECLARE
    _conname TEXT;
    _condef  TEXT;
BEGIN
    SELECT con.conname, pg_get_constraintdef(con.oid) INTO _conname, _condef
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    WHERE rel.relname = 'users'
      AND con.contype = 'c'
      AND pg_get_constraintdef(con.oid) ILIKE '%role%'
    LIMIT 1;

    IF _conname IS NOT NULL AND _condef NOT ILIKE '%sales coordinator%' THEN
        EXECUTE format('ALTER TABLE users DROP CONSTRAINT %I', _conname);
        ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN (
            'admin', 'rep', 'maintenance', 'supervisor',
            'sales manager', 'biomedical manager', 'sales coordinator'
        ));
    END IF;
END $$;

-- ── QA fixes: drop request_source, require validity/delivery/payment terms,
-- ── zero-default VAT rate ────────────────────────────────────────────────────
-- request_source is no longer recorded at all.
ALTER TABLE quotation_requests  DROP COLUMN IF EXISTS request_source;
ALTER TABLE quotation_revisions DROP COLUMN IF EXISTS request_source;

-- Backfill any existing NULLs before enforcing NOT NULL below.
UPDATE quotation_requests  SET validity_days  = 30                    WHERE validity_days  IS NULL;
UPDATE quotation_requests  SET delivery_terms = 'Immediate'           WHERE delivery_terms IS NULL;
UPDATE quotation_requests  SET payment_terms  = 'Cash on Delivery'    WHERE payment_terms  IS NULL;
UPDATE quotation_revisions SET validity_days  = 30                    WHERE validity_days  IS NULL;
UPDATE quotation_revisions SET delivery_terms = 'Immediate'           WHERE delivery_terms IS NULL;
UPDATE quotation_revisions SET payment_terms  = 'Cash on Delivery'    WHERE payment_terms  IS NULL;

ALTER TABLE quotation_requests  ALTER COLUMN validity_days  SET NOT NULL;
ALTER TABLE quotation_requests  ALTER COLUMN delivery_terms SET NOT NULL;
ALTER TABLE quotation_requests  ALTER COLUMN payment_terms  SET NOT NULL;
ALTER TABLE quotation_revisions ALTER COLUMN validity_days  SET NOT NULL;
ALTER TABLE quotation_revisions ALTER COLUMN delivery_terms SET NOT NULL;
ALTER TABLE quotation_revisions ALTER COLUMN payment_terms  SET NOT NULL;

-- New default VAT rate is 0% (was 15%). Existing rows keep their stored value;
-- this only changes what future inserts get when vat_rate is omitted.
ALTER TABLE quotation_requests ALTER COLUMN vat_rate SET DEFAULT 0;

-- ── Quantity is always a whole number in this business — narrow from
-- ── NUMERIC(14,3) to INTEGER. Any existing fractional test rows are rounded
-- ── to the nearest whole number rather than failing the migration. Safe to
-- ── re-run: ALTER COLUMN ... TYPE INTEGER is a no-op once the column is
-- ── already INTEGER (confirmed empirically — round() still applies cleanly
-- ── via the implicit int->numeric cast, so this never errors on rerun).
ALTER TABLE quotation_lines          ALTER COLUMN quantity TYPE INTEGER USING ROUND(quantity)::INTEGER;
ALTER TABLE quotation_revision_lines ALTER COLUMN quantity TYPE INTEGER USING ROUND(quantity)::INTEGER;

-- ── A quotation must never have two lines for the same product — the UI
-- ── now blocks this too, but this is the DB-level backstop (matches the
-- ── existing UNIQUE(quotation_id, line_no) precedent above).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'quotation_lines'::regclass
          AND conname  = 'quotation_lines_quotation_id_product_id_key'
    ) THEN
        ALTER TABLE quotation_lines
            ADD CONSTRAINT quotation_lines_quotation_id_product_id_key
            UNIQUE (quotation_id, product_id);
    END IF;
END $$;

-- ── Line items are now unlimited (was capped at 14 per quotation) --
-- drop the upper bound on the existing live table, keep the lower bound.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'quotation_lines'::regclass
          AND conname  = 'quotation_lines_line_no_check'
          AND pg_get_constraintdef(oid) LIKE '%<=%14%'
    ) THEN
        ALTER TABLE quotation_lines DROP CONSTRAINT quotation_lines_line_no_check;
        ALTER TABLE quotation_lines ADD CONSTRAINT quotation_lines_line_no_check CHECK (line_no >= 1);
    END IF;
END $$;
