-- migrations/sample_requests_schema.sql
-- Idempotent — safe to re-run on every app startup.

CREATE TABLE IF NOT EXISTS sample_requests (
    sample_request_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number      TEXT    NOT NULL UNIQUE,
    customer_id           INTEGER NOT NULL REFERENCES customers(customer_id),
    rep_user_id            INTEGER NOT NULL REFERENCES users(user_id),

    request_date            DATE    NOT NULL DEFAULT CURRENT_DATE,
    delivery_date             DATE,
    remarks                   TEXT,

    status  TEXT NOT NULL DEFAULT 'IN_REVIEW' CHECK (status IN (
                 'IN_REVIEW', 'EDIT_REQUESTED', 'REJECTED', 'APPROVED', 'DONE', 'WITHDRAWN'
             )),
    version  INTEGER NOT NULL DEFAULT 0,

    submitted_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    submitted_by  INTEGER NOT NULL REFERENCES users(user_id),

    manager_user_id      INTEGER REFERENCES users(user_id),
    manager_decided_at   TIMESTAMPTZ,
    manager_comment       TEXT,

    coordinator_user_id      INTEGER REFERENCES users(user_id),
    coordinator_done_at       TIMESTAMPTZ,
    coordinator_note           TEXT,
    odoo_reference               TEXT,

    withdrawn_at       TIMESTAMPTZ,
    withdrawn_by        INTEGER REFERENCES users(user_id),
    withdrawal_reason    TEXT,

    is_deleted   BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMPTZ,
    deleted_by     INTEGER REFERENCES users(user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sr_odoo_ref_unique
    ON sample_requests (odoo_reference) WHERE odoo_reference IS NOT NULL;

CREATE TABLE IF NOT EXISTS sample_request_lines (
    line_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_request_id  BIGINT NOT NULL REFERENCES sample_requests(sample_request_id) ON DELETE CASCADE,
    line_no            SMALLINT NOT NULL CHECK (line_no BETWEEN 1 AND 50),
    product_id         TEXT NOT NULL REFERENCES items(product_id),
    quantity           INTEGER NOT NULL CHECK (quantity > 0),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (sample_request_id, line_no)
);

CREATE TABLE IF NOT EXISTS sample_request_revisions (
    revision_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_request_id   BIGINT NOT NULL REFERENCES sample_requests(sample_request_id) ON DELETE CASCADE,
    revision_no         SMALLINT NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by            INTEGER NOT NULL REFERENCES users(user_id),
    customer_id            INTEGER NOT NULL REFERENCES customers(customer_id),
    request_date            DATE NOT NULL,
    delivery_date             DATE,
    remarks                   TEXT,
    UNIQUE (sample_request_id, revision_no)
);

CREATE TABLE IF NOT EXISTS sample_request_revision_lines (
    revision_line_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id              BIGINT NOT NULL REFERENCES sample_request_revisions(revision_id) ON DELETE CASCADE,
    line_no                    SMALLINT NOT NULL,
    product_id                  TEXT NOT NULL REFERENCES items(product_id),
    article_number_snapshot      TEXT,
    description_snapshot          TEXT,
    quantity                        INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS sample_request_status_events (
    event_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_request_id   BIGINT NOT NULL REFERENCES sample_requests(sample_request_id) ON DELETE CASCADE,
    event_type          TEXT NOT NULL CHECK (event_type IN (
                             'SUBMITTED', 'RESUBMITTED', 'EDIT_REQUESTED', 'APPROVED',
                             'REJECTED', 'WITHDRAWN', 'RETURNED_FOR_REVISION', 'MARKED_DONE'
                         )),
    actor_user_id       INTEGER NOT NULL REFERENCES users(user_id),
    from_status          TEXT,
    to_status              TEXT NOT NULL,
    comment                  TEXT,
    revision_id               BIGINT REFERENCES sample_request_revisions(revision_id),
    at_utc                      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sample_request_number_counters (
    year     INTEGER PRIMARY KEY,
    last_seq INTEGER NOT NULL DEFAULT 0
);

-- Schema evolution: delivery_date moved from per-line to request-level (one
-- delivery date per request, not per item) — idempotent ALTERs for the case
-- where these tables already existed with the old column shape.
ALTER TABLE sample_requests ADD COLUMN IF NOT EXISTS delivery_date DATE;
ALTER TABLE sample_request_lines DROP COLUMN IF EXISTS delivery_date;
ALTER TABLE sample_request_revisions ADD COLUMN IF NOT EXISTS delivery_date DATE;
ALTER TABLE sample_request_revision_lines DROP COLUMN IF EXISTS delivery_date;

CREATE INDEX IF NOT EXISTS idx_sr_status        ON sample_requests(status);
CREATE INDEX IF NOT EXISTS idx_sr_rep            ON sample_requests(rep_user_id);
CREATE INDEX IF NOT EXISTS idx_sr_customer       ON sample_requests(customer_id);
CREATE INDEX IF NOT EXISTS idx_sr_manager        ON sample_requests(manager_user_id);
CREATE INDEX IF NOT EXISTS idx_sr_coordinator    ON sample_requests(coordinator_user_id);
CREATE INDEX IF NOT EXISTS idx_srl_request       ON sample_request_lines(sample_request_id);
CREATE INDEX IF NOT EXISTS idx_srl_product       ON sample_request_lines(product_id);
CREATE INDEX IF NOT EXISTS idx_srev_request      ON sample_request_revisions(sample_request_id, revision_no);
CREATE INDEX IF NOT EXISTS idx_srse_request      ON sample_request_status_events(sample_request_id, at_utc);
CREATE INDEX IF NOT EXISTS idx_sr_customer_done  ON sample_requests(customer_id, status) WHERE status = 'DONE';
CREATE INDEX IF NOT EXISTS idx_sr_rep_done       ON sample_requests(rep_user_id, status) WHERE status = 'DONE';
