-- migrations/targets_schema.sql
-- Idempotent. Safe to re-run on every startup.

-- ── product_categories ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS product_categories (
    product_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_unit_id    INTEGER NOT NULL REFERENCES business_units(business_unit_id),
    name                TEXT    NOT NULL,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (business_unit_id, name)
);

-- ── business_lines: add product_category_id FK (nullable, non-breaking) ──────
ALTER TABLE business_lines
    ADD COLUMN IF NOT EXISTS product_category_id INTEGER
    REFERENCES product_categories(product_category_id);

-- ── target_year ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS target_year (
    year           INTEGER       PRIMARY KEY,
    target_amount  NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (target_amount >= 0),
    target_visits  INTEGER       NOT NULL DEFAULT 0 CHECK (target_visits >= 0),
    status         TEXT          NOT NULL DEFAULT 'DRAFT'
                   CHECK (status IN ('DRAFT', 'ACTIVE', 'LOCKED')),
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by     INTEGER       REFERENCES users(user_id),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_by     INTEGER       REFERENCES users(user_id)
);

-- ── target_rep ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS target_rep (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year           INTEGER       NOT NULL REFERENCES target_year(year) ON DELETE CASCADE,
    user_id        INTEGER       NOT NULL REFERENCES users(user_id),
    target_amount  NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (target_amount >= 0),
    target_visits  INTEGER       NOT NULL DEFAULT 0 CHECK (target_visits >= 0),
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by     INTEGER       REFERENCES users(user_id),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_by     INTEGER       REFERENCES users(user_id),
    UNIQUE (year, user_id)
);

-- ── target_breakdown ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS target_breakdown (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_rep_id       BIGINT        NOT NULL REFERENCES target_rep(id) ON DELETE CASCADE,
    year                INTEGER       NOT NULL,
    user_id             INTEGER       NOT NULL,
    breakdown_level     TEXT          NOT NULL
                        CHECK (breakdown_level IN (
                            'rep','customer','business_unit',
                            'product_category','business_line','article'
                        )),
    customer_id         INTEGER       REFERENCES customers(customer_id),
    business_unit_id    INTEGER       REFERENCES business_units(business_unit_id),
    product_category_id INTEGER       REFERENCES product_categories(product_category_id),
    business_line_id    INTEGER       REFERENCES business_lines(business_line_id),
    article_id          TEXT          REFERENCES items(product_id),
    target_amount       NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (target_amount >= 0),
    target_visits       INTEGER       NOT NULL DEFAULT 0 CHECK (target_visits >= 0),
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by          INTEGER       REFERENCES users(user_id),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_by          INTEGER       REFERENCES users(user_id)
);

-- ── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_product_categories_bu ON product_categories(business_unit_id);
CREATE INDEX IF NOT EXISTS idx_business_lines_cat    ON business_lines(product_category_id);
CREATE INDEX IF NOT EXISTS idx_target_rep_year       ON target_rep(year);
CREATE INDEX IF NOT EXISTS idx_target_rep_user       ON target_rep(user_id);
CREATE INDEX IF NOT EXISTS idx_target_bd_rep         ON target_breakdown(target_rep_id);
CREATE INDEX IF NOT EXISTS idx_target_bd_year_user   ON target_breakdown(year, user_id);
CREATE INDEX IF NOT EXISTS idx_target_bd_customer    ON target_breakdown(customer_id);
CREATE INDEX IF NOT EXISTS idx_target_bd_bu          ON target_breakdown(business_unit_id);

-- ── Reporting Views ───────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW v_target_year_summary AS
SELECT
    ty.year,
    ty.target_amount,
    ty.target_visits,
    CASE WHEN ty.target_visits > 0
         THEN ROUND(ty.target_amount / ty.target_visits, 2)
         ELSE NULL END                                    AS productivity,
    ty.status,
    COUNT(DISTINCT tr.id)                                 AS rep_count,
    COALESCE(SUM(tr.target_amount), 0)                    AS allocated_amount,
    COALESCE(SUM(tr.target_visits), 0)                    AS allocated_visits,
    ty.target_amount - COALESCE(SUM(tr.target_amount), 0) AS remaining_amount,
    ty.target_visits - COALESCE(SUM(tr.target_visits), 0) AS remaining_visits,
    ty.created_at,
    ty.updated_at
FROM target_year ty
LEFT JOIN target_rep tr ON tr.year = ty.year
GROUP BY ty.year, ty.target_amount, ty.target_visits,
         ty.status, ty.created_at, ty.updated_at;

CREATE OR REPLACE VIEW v_target_rep_summary AS
SELECT
    tr.id                                                  AS target_rep_id,
    tr.year,
    tr.user_id,
    u.name                                                 AS rep_name,
    u.region                                               AS rep_region,
    u.role                                                 AS rep_role,
    tr.target_amount,
    tr.target_visits,
    CASE WHEN tr.target_visits > 0
         THEN ROUND(tr.target_amount / tr.target_visits, 2)
         ELSE NULL END                                     AS productivity,
    COALESCE(SUM(tb.target_amount), 0)                     AS breakdown_amount,
    COALESCE(SUM(tb.target_visits), 0)                     AS breakdown_visits,
    tr.target_amount - COALESCE(SUM(tb.target_amount), 0)  AS unallocated_amount,
    tr.target_visits - COALESCE(SUM(tb.target_visits), 0)  AS unallocated_visits,
    COUNT(tb.id)                                           AS breakdown_row_count
FROM target_rep tr
JOIN users u ON u.user_id = tr.user_id
LEFT JOIN target_breakdown tb ON tb.target_rep_id = tr.id
GROUP BY tr.id, tr.year, tr.user_id, u.name,
         u.region, u.role, tr.target_amount, tr.target_visits;

DROP VIEW IF EXISTS v_target_breakdown_reporting;
CREATE OR REPLACE VIEW v_target_breakdown_reporting AS
SELECT
    tb.id,
    tb.target_rep_id,
    tb.year,
    tb.breakdown_level,
    tb.user_id,
    u.name                  AS rep_name,
    u.region                AS rep_region,
    u.role                  AS rep_role,
    tb.customer_id,
    c.account_name          AS customer_name,
    c.sector                AS customer_sector,
    c.region                AS customer_region,
    tb.business_unit_id,
    bu.name                 AS business_unit_name,
    tb.product_category_id,
    pc.name                 AS product_category_name,
    tb.business_line_id,
    bl.name                 AS business_line_name,
    tb.article_id           AS product_id,
    i.article_number,
    i.description           AS article_description,
    tb.target_amount,
    tb.target_visits,
    CASE WHEN tb.target_visits > 0
         THEN ROUND(tb.target_amount / tb.target_visits, 2)
         ELSE NULL END      AS productivity,
    tb.created_at,
    tb.updated_at
FROM target_breakdown tb
JOIN  users              u  ON u.user_id                 = tb.user_id
LEFT JOIN customers      c  ON c.customer_id             = tb.customer_id
LEFT JOIN business_units bu ON bu.business_unit_id       = tb.business_unit_id
LEFT JOIN product_categories pc ON pc.product_category_id = tb.product_category_id
LEFT JOIN business_lines bl ON bl.business_line_id       = tb.business_line_id
LEFT JOIN items           i ON i.product_id              = tb.article_id;

-- Level-specific actual vs target views (no cross-level double counting)

CREATE OR REPLACE VIEW v_actual_vs_target_rep AS
SELECT
    tr.year, tr.user_id, u.name AS rep_name, u.region AS rep_region,
    tr.target_amount, tr.target_visits,
    COUNT(DISTINCT v.visit_id)  AS actual_visits,
    CASE WHEN tr.target_visits > 0
         THEN ROUND(COUNT(DISTINCT v.visit_id)::NUMERIC / tr.target_visits * 100, 1)
         ELSE NULL END          AS visit_achievement_pct,
    NULL::NUMERIC               AS actual_sales_amount
FROM target_rep tr
JOIN users u ON u.user_id = tr.user_id
LEFT JOIN visits v
    ON  v.user_id    = tr.user_id
    AND EXTRACT(YEAR FROM COALESCE(v.submitted_at_local, v.submitted_at_utc)) = tr.year
    AND v.is_deleted = FALSE
GROUP BY tr.year, tr.user_id, u.name, u.region, tr.target_amount, tr.target_visits;

CREATE OR REPLACE VIEW v_actual_vs_target_customer AS
SELECT
    tb.year, tb.user_id, u.name AS rep_name,
    tb.customer_id, c.account_name AS customer_name,
    tb.target_amount, tb.target_visits,
    COUNT(DISTINCT v.visit_id)  AS actual_visits,
    CASE WHEN tb.target_visits > 0
         THEN ROUND(COUNT(DISTINCT v.visit_id)::NUMERIC / tb.target_visits * 100, 1)
         ELSE NULL END          AS visit_achievement_pct,
    NULL::NUMERIC               AS actual_sales_amount
FROM target_breakdown tb
JOIN users u ON u.user_id = tb.user_id
LEFT JOIN customers c ON c.customer_id = tb.customer_id
LEFT JOIN visits v
    ON  v.user_id     = tb.user_id
    AND v.customer_id = tb.customer_id
    AND EXTRACT(YEAR FROM COALESCE(v.submitted_at_local, v.submitted_at_utc)) = tb.year
    AND v.is_deleted  = FALSE
WHERE tb.breakdown_level = 'customer'
GROUP BY tb.year, tb.user_id, u.name, tb.customer_id, c.account_name,
         tb.target_amount, tb.target_visits;

CREATE OR REPLACE VIEW v_actual_vs_target_business_unit AS
SELECT
    tb.year, tb.user_id, u.name AS rep_name,
    tb.business_unit_id, bu.name AS business_unit_name,
    tb.target_amount, tb.target_visits,
    COUNT(DISTINCT v.visit_id)  AS actual_visits,
    CASE WHEN tb.target_visits > 0
         THEN ROUND(COUNT(DISTINCT v.visit_id)::NUMERIC / tb.target_visits * 100, 1)
         ELSE NULL END          AS visit_achievement_pct,
    NULL::NUMERIC               AS actual_sales_amount
FROM target_breakdown tb
JOIN users u ON u.user_id = tb.user_id
LEFT JOIN business_units bu ON bu.business_unit_id = tb.business_unit_id
LEFT JOIN visits v
    ON  v.user_id          = tb.user_id
    AND v.business_line_id IN (
        SELECT business_line_id FROM business_lines
        WHERE business_unit_id = tb.business_unit_id
    )
    AND EXTRACT(YEAR FROM COALESCE(v.submitted_at_local, v.submitted_at_utc)) = tb.year
    AND v.is_deleted       = FALSE
WHERE tb.breakdown_level = 'business_unit'
GROUP BY tb.year, tb.user_id, u.name, tb.business_unit_id, bu.name,
         tb.target_amount, tb.target_visits;

CREATE OR REPLACE VIEW v_actual_vs_target_product_category AS
SELECT
    tb.year, tb.user_id, u.name AS rep_name,
    tb.product_category_id, pc.name AS product_category_name,
    tb.target_amount, tb.target_visits,
    COUNT(DISTINCT v.visit_id)  AS actual_visits,
    CASE WHEN tb.target_visits > 0
         THEN ROUND(COUNT(DISTINCT v.visit_id)::NUMERIC / tb.target_visits * 100, 1)
         ELSE NULL END          AS visit_achievement_pct,
    NULL::NUMERIC               AS actual_sales_amount
FROM target_breakdown tb
JOIN users u ON u.user_id = tb.user_id
LEFT JOIN product_categories pc ON pc.product_category_id = tb.product_category_id
LEFT JOIN visits v
    ON  v.user_id          = tb.user_id
    AND v.business_line_id IN (
        SELECT business_line_id FROM business_lines
        WHERE product_category_id = tb.product_category_id
    )
    AND EXTRACT(YEAR FROM COALESCE(v.submitted_at_local, v.submitted_at_utc)) = tb.year
    AND v.is_deleted       = FALSE
WHERE tb.breakdown_level = 'product_category'
GROUP BY tb.year, tb.user_id, u.name, tb.product_category_id, pc.name,
         tb.target_amount, tb.target_visits;

CREATE OR REPLACE VIEW v_actual_vs_target_business_line AS
SELECT
    tb.year, tb.user_id, u.name AS rep_name,
    tb.business_line_id, bl.name AS business_line_name,
    tb.target_amount, tb.target_visits,
    COUNT(DISTINCT v.visit_id)  AS actual_visits,
    CASE WHEN tb.target_visits > 0
         THEN ROUND(COUNT(DISTINCT v.visit_id)::NUMERIC / tb.target_visits * 100, 1)
         ELSE NULL END          AS visit_achievement_pct,
    NULL::NUMERIC               AS actual_sales_amount
FROM target_breakdown tb
JOIN users u ON u.user_id = tb.user_id
LEFT JOIN business_lines bl ON bl.business_line_id = tb.business_line_id
LEFT JOIN visits v
    ON  v.user_id          = tb.user_id
    AND v.business_line_id = tb.business_line_id
    AND EXTRACT(YEAR FROM COALESCE(v.submitted_at_local, v.submitted_at_utc)) = tb.year
    AND v.is_deleted       = FALSE
WHERE tb.breakdown_level = 'business_line'
GROUP BY tb.year, tb.user_id, u.name, tb.business_line_id, bl.name,
         tb.target_amount, tb.target_visits;

CREATE OR REPLACE VIEW v_actual_vs_target_article AS
SELECT
    tb.year, tb.user_id, u.name AS rep_name,
    tb.article_id AS product_id, i.article_number, i.description AS article_description,
    tb.target_amount, tb.target_visits,
    COUNT(DISTINCT v.visit_id)  AS actual_visits,
    CASE WHEN tb.target_visits > 0
         THEN ROUND(COUNT(DISTINCT v.visit_id)::NUMERIC / tb.target_visits * 100, 1)
         ELSE NULL END          AS visit_achievement_pct,
    NULL::NUMERIC               AS actual_sales_amount
FROM target_breakdown tb
JOIN users u ON u.user_id = tb.user_id
LEFT JOIN items i ON i.product_id = tb.article_id
LEFT JOIN visits v
    ON  v.user_id    = tb.user_id
    AND v.product_id = tb.article_id
    AND EXTRACT(YEAR FROM COALESCE(v.submitted_at_local, v.submitted_at_utc)) = tb.year
    AND v.is_deleted = FALSE
WHERE tb.breakdown_level = 'article'
GROUP BY tb.year, tb.user_id, u.name, tb.article_id, i.article_number,
         i.description, tb.target_amount, tb.target_visits;
