-- migrations/targets_schema.sql
-- Drops old target tables and recreates from scratch.
-- product_categories is retained (shared dimension table).

DROP TABLE IF EXISTS target_breakdown CASCADE;
DROP TABLE IF EXISTS target_rep CASCADE;
DROP TABLE IF EXISTS target_year CASCADE;

-- ── product_categories (keep if exists, create if not) ────────────────────────
CREATE TABLE IF NOT EXISTS product_categories (
    product_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_unit_id    INTEGER NOT NULL REFERENCES business_units(business_unit_id),
    name                TEXT    NOT NULL,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (business_unit_id, name)
);

ALTER TABLE business_lines
    ADD COLUMN IF NOT EXISTS product_category_id INTEGER
    REFERENCES product_categories(product_category_id);

-- ── target_year ───────────────────────────────────────────────────────────────
CREATE TABLE target_year (
    year           INTEGER       PRIMARY KEY,
    budget_amount  NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (budget_amount >= 0),
    budget_visits  INTEGER       NOT NULL DEFAULT 0 CHECK (budget_visits >= 0),
    status         TEXT          NOT NULL DEFAULT 'DRAFT'
                   CHECK (status IN ('DRAFT', 'ACTIVE', 'LOCKED')),
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by     INTEGER       REFERENCES users(user_id),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_by     INTEGER       REFERENCES users(user_id)
);

-- ── target_rep (junction only — no amounts) ───────────────────────────────────
CREATE TABLE target_rep (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year       INTEGER     NOT NULL REFERENCES target_year(year) ON DELETE CASCADE,
    user_id    INTEGER     NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by INTEGER     REFERENCES users(user_id),
    UNIQUE (year, user_id)
);

-- ── target_breakdown ──────────────────────────────────────────────────────────
CREATE TABLE target_breakdown (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_rep_id       BIGINT        NOT NULL REFERENCES target_rep(id) ON DELETE CASCADE,
    year                INTEGER       NOT NULL,
    user_id             INTEGER       NOT NULL REFERENCES users(user_id),
    breakdown_level     TEXT          NOT NULL
                        CHECK (breakdown_level IN (
                            'customer','business_unit','product_category',
                            'business_line','article'
                        )),
    customer_id         INTEGER       REFERENCES customers(customer_id),
    business_unit_id    INTEGER       REFERENCES business_units(business_unit_id),
    product_category_id INTEGER       REFERENCES product_categories(product_category_id),
    business_line_id    INTEGER       REFERENCES business_lines(business_line_id),
    article_id          TEXT          REFERENCES items(product_id),
    target_amount       NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (target_amount >= 0),
    target_visits       INTEGER       NOT NULL DEFAULT 0 CHECK (target_visits >= 0),
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by          INTEGER       REFERENCES users(user_id),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_by          INTEGER       REFERENCES users(user_id)
);

-- ── Indexes ───────────────────────────────────────────────────────────────────
CREATE INDEX idx_product_categories_bu ON product_categories(business_unit_id);
CREATE INDEX idx_business_lines_cat    ON business_lines(product_category_id);
CREATE INDEX idx_target_rep_year       ON target_rep(year);
CREATE INDEX idx_target_rep_user       ON target_rep(user_id);
CREATE INDEX idx_target_bd_rep         ON target_breakdown(target_rep_id);
CREATE INDEX idx_target_bd_year_user   ON target_breakdown(year, user_id);
CREATE INDEX idx_target_bd_customer    ON target_breakdown(customer_id);
CREATE INDEX idx_target_bd_bu          ON target_breakdown(business_unit_id);
CREATE INDEX idx_target_bd_level       ON target_breakdown(breakdown_level);

CREATE UNIQUE INDEX uq_target_breakdown ON target_breakdown (
    target_rep_id,
    breakdown_level,
    COALESCE(customer_id,          -1),
    COALESCE(business_unit_id,     -1),
    COALESCE(product_category_id,  -1),
    COALESCE(business_line_id,     -1),
    COALESCE(article_id,           '')
);

-- ── Views ─────────────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW v_target_year_summary AS
SELECT
    ty.year,
    ty.budget_amount,
    ty.budget_visits,
    ty.status,
    COUNT(DISTINCT tr.id)                                        AS rep_count,
    COALESCE(SUM(tb.target_amount), 0)                           AS planned_amount,
    COALESCE(SUM(tb.target_visits), 0)                           AS planned_visits,
    ty.budget_amount - COALESCE(SUM(tb.target_amount), 0)        AS remaining_amount,
    ty.budget_visits - COALESCE(SUM(tb.target_visits), 0)        AS remaining_visits,
    CASE WHEN ty.budget_amount > 0
         THEN ROUND(COALESCE(SUM(tb.target_amount), 0) / ty.budget_amount * 100, 1)
         ELSE NULL END                                           AS planned_pct,
    ty.created_at,
    ty.updated_at
FROM target_year ty
LEFT JOIN target_rep tr ON tr.year = ty.year
LEFT JOIN target_breakdown tb ON tb.target_rep_id = tr.id
GROUP BY ty.year, ty.budget_amount, ty.budget_visits,
         ty.status, ty.created_at, ty.updated_at;

CREATE OR REPLACE VIEW v_target_rep_summary AS
SELECT
    tr.id                                                         AS target_rep_id,
    tr.year,
    tr.user_id,
    u.name                                                        AS rep_name,
    u.region                                                      AS rep_region,
    u.role                                                        AS rep_role,
    ty.budget_amount                                              AS year_budget_amount,
    ty.budget_visits                                              AS year_budget_visits,
    ty.status                                                     AS year_status,
    COALESCE(SUM(tb.target_amount), 0)                            AS planned_amount,
    COALESCE(SUM(tb.target_visits), 0)                            AS planned_visits,
    COUNT(tb.id)                                                  AS breakdown_row_count,
    CASE WHEN ty.budget_amount > 0
         THEN ROUND(COALESCE(SUM(tb.target_amount), 0) / ty.budget_amount * 100, 1)
         ELSE NULL END                                            AS pct_of_year_budget
FROM target_rep tr
JOIN users       u  ON u.user_id  = tr.user_id
JOIN target_year ty ON ty.year    = tr.year
LEFT JOIN target_breakdown tb ON tb.target_rep_id = tr.id
GROUP BY tr.id, tr.year, tr.user_id, u.name, u.region, u.role,
         ty.budget_amount, ty.budget_visits, ty.status;

CREATE OR REPLACE VIEW v_target_breakdown AS
SELECT
    tb.id,
    tb.target_rep_id,
    tb.year,
    tb.breakdown_level,
    tb.user_id,
    u.name                    AS rep_name,
    u.region                  AS rep_region,
    u.role                    AS rep_role,
    ty.budget_amount          AS year_budget_amount,
    ty.budget_visits          AS year_budget_visits,
    ty.status                 AS year_status,
    tb.customer_id,
    c.account_name            AS customer_name,
    c.sector                  AS customer_sector,
    c.region                  AS customer_region,
    tb.business_unit_id,
    bu.name                   AS business_unit_name,
    tb.product_category_id,
    pc.name                   AS product_category_name,
    tb.business_line_id,
    bl.name                   AS business_line_name,
    tb.article_id             AS product_id,
    i.article_number,
    i.description             AS article_description,
    tb.target_amount,
    tb.target_visits,
    CASE WHEN tb.target_visits > 0
         THEN ROUND(tb.target_amount / tb.target_visits, 2)
         ELSE NULL END        AS productivity,
    tb.created_at,
    tb.updated_at
FROM target_breakdown tb
JOIN  target_year        ty ON ty.year                    = tb.year
JOIN  users              u  ON u.user_id                  = tb.user_id
LEFT JOIN customers      c  ON c.customer_id              = tb.customer_id
LEFT JOIN business_units bu ON bu.business_unit_id        = tb.business_unit_id
LEFT JOIN product_categories pc ON pc.product_category_id = tb.product_category_id
LEFT JOIN business_lines bl ON bl.business_line_id        = tb.business_line_id
LEFT JOIN items          i  ON i.product_id               = tb.article_id;

-- Level-specific actual vs target views
CREATE OR REPLACE VIEW v_actual_vs_target_customer AS
SELECT
    vt.id, vt.target_rep_id, vt.year, vt.breakdown_level,
    vt.user_id, vt.rep_name, vt.rep_region, vt.rep_role,
    vt.year_budget_amount, vt.year_budget_visits, vt.year_status,
    vt.customer_id, vt.customer_name, vt.customer_sector, vt.customer_region,
    vt.business_unit_id, vt.business_unit_name,
    vt.product_category_id, vt.product_category_name,
    vt.business_line_id, vt.business_line_name,
    vt.product_id, vt.article_number, vt.article_description,
    vt.target_amount, vt.target_visits, vt.productivity,
    vt.created_at, vt.updated_at,
    COUNT(DISTINCT v.visit_id)   AS actual_visits,
    CASE WHEN vt.target_visits > 0
         THEN ROUND(COUNT(DISTINCT v.visit_id)::NUMERIC / vt.target_visits * 100, 1)
         ELSE NULL END           AS visit_achievement_pct,
    NULL::NUMERIC                AS actual_sales_amount
FROM v_target_breakdown vt
LEFT JOIN visits v
    ON  v.user_id     = vt.user_id
    AND v.customer_id = vt.customer_id
    AND EXTRACT(YEAR FROM COALESCE(v.submitted_at_local, v.submitted_at_utc)) = vt.year
    AND v.is_deleted  = FALSE
WHERE vt.breakdown_level = 'customer'
GROUP BY vt.id, vt.target_rep_id, vt.year, vt.breakdown_level,
    vt.user_id, vt.rep_name, vt.rep_region, vt.rep_role,
    vt.year_budget_amount, vt.year_budget_visits, vt.year_status,
    vt.customer_id, vt.customer_name, vt.customer_sector, vt.customer_region,
    vt.business_unit_id, vt.business_unit_name,
    vt.product_category_id, vt.product_category_name,
    vt.business_line_id, vt.business_line_name,
    vt.product_id, vt.article_number, vt.article_description,
    vt.target_amount, vt.target_visits, vt.productivity,
    vt.created_at, vt.updated_at;

CREATE OR REPLACE VIEW v_actual_vs_target_business_unit AS
SELECT
    vt.id, vt.target_rep_id, vt.year, vt.breakdown_level,
    vt.user_id, vt.rep_name, vt.rep_region, vt.rep_role,
    vt.year_budget_amount, vt.year_budget_visits, vt.year_status,
    vt.customer_id, vt.customer_name, vt.customer_sector, vt.customer_region,
    vt.business_unit_id, vt.business_unit_name,
    vt.product_category_id, vt.product_category_name,
    vt.business_line_id, vt.business_line_name,
    vt.product_id, vt.article_number, vt.article_description,
    vt.target_amount, vt.target_visits, vt.productivity,
    vt.created_at, vt.updated_at,
    COUNT(DISTINCT v.visit_id)   AS actual_visits,
    CASE WHEN vt.target_visits > 0
         THEN ROUND(COUNT(DISTINCT v.visit_id)::NUMERIC / vt.target_visits * 100, 1)
         ELSE NULL END           AS visit_achievement_pct,
    NULL::NUMERIC                AS actual_sales_amount
FROM v_target_breakdown vt
LEFT JOIN visits v
    ON  v.user_id          = vt.user_id
    AND v.business_line_id IN (
        SELECT business_line_id FROM business_lines
        WHERE business_unit_id = vt.business_unit_id
    )
    AND EXTRACT(YEAR FROM COALESCE(v.submitted_at_local, v.submitted_at_utc)) = vt.year
    AND v.is_deleted = FALSE
WHERE vt.breakdown_level = 'business_unit'
GROUP BY vt.id, vt.target_rep_id, vt.year, vt.breakdown_level,
    vt.user_id, vt.rep_name, vt.rep_region, vt.rep_role,
    vt.year_budget_amount, vt.year_budget_visits, vt.year_status,
    vt.customer_id, vt.customer_name, vt.customer_sector, vt.customer_region,
    vt.business_unit_id, vt.business_unit_name,
    vt.product_category_id, vt.product_category_name,
    vt.business_line_id, vt.business_line_name,
    vt.product_id, vt.article_number, vt.article_description,
    vt.target_amount, vt.target_visits, vt.productivity,
    vt.created_at, vt.updated_at;

CREATE OR REPLACE VIEW v_actual_vs_target_product_category AS
SELECT
    vt.id, vt.target_rep_id, vt.year, vt.breakdown_level,
    vt.user_id, vt.rep_name, vt.rep_region, vt.rep_role,
    vt.year_budget_amount, vt.year_budget_visits, vt.year_status,
    vt.customer_id, vt.customer_name, vt.customer_sector, vt.customer_region,
    vt.business_unit_id, vt.business_unit_name,
    vt.product_category_id, vt.product_category_name,
    vt.business_line_id, vt.business_line_name,
    vt.product_id, vt.article_number, vt.article_description,
    vt.target_amount, vt.target_visits, vt.productivity,
    vt.created_at, vt.updated_at,
    COUNT(DISTINCT v.visit_id)   AS actual_visits,
    CASE WHEN vt.target_visits > 0
         THEN ROUND(COUNT(DISTINCT v.visit_id)::NUMERIC / vt.target_visits * 100, 1)
         ELSE NULL END           AS visit_achievement_pct,
    NULL::NUMERIC                AS actual_sales_amount
FROM v_target_breakdown vt
LEFT JOIN visits v
    ON  v.user_id          = vt.user_id
    AND v.business_line_id IN (
        SELECT business_line_id FROM business_lines
        WHERE product_category_id = vt.product_category_id
    )
    AND EXTRACT(YEAR FROM COALESCE(v.submitted_at_local, v.submitted_at_utc)) = vt.year
    AND v.is_deleted = FALSE
WHERE vt.breakdown_level = 'product_category'
GROUP BY vt.id, vt.target_rep_id, vt.year, vt.breakdown_level,
    vt.user_id, vt.rep_name, vt.rep_region, vt.rep_role,
    vt.year_budget_amount, vt.year_budget_visits, vt.year_status,
    vt.customer_id, vt.customer_name, vt.customer_sector, vt.customer_region,
    vt.business_unit_id, vt.business_unit_name,
    vt.product_category_id, vt.product_category_name,
    vt.business_line_id, vt.business_line_name,
    vt.product_id, vt.article_number, vt.article_description,
    vt.target_amount, vt.target_visits, vt.productivity,
    vt.created_at, vt.updated_at;

CREATE OR REPLACE VIEW v_actual_vs_target_business_line AS
SELECT
    vt.id, vt.target_rep_id, vt.year, vt.breakdown_level,
    vt.user_id, vt.rep_name, vt.rep_region, vt.rep_role,
    vt.year_budget_amount, vt.year_budget_visits, vt.year_status,
    vt.customer_id, vt.customer_name, vt.customer_sector, vt.customer_region,
    vt.business_unit_id, vt.business_unit_name,
    vt.product_category_id, vt.product_category_name,
    vt.business_line_id, vt.business_line_name,
    vt.product_id, vt.article_number, vt.article_description,
    vt.target_amount, vt.target_visits, vt.productivity,
    vt.created_at, vt.updated_at,
    COUNT(DISTINCT v.visit_id)   AS actual_visits,
    CASE WHEN vt.target_visits > 0
         THEN ROUND(COUNT(DISTINCT v.visit_id)::NUMERIC / vt.target_visits * 100, 1)
         ELSE NULL END           AS visit_achievement_pct,
    NULL::NUMERIC                AS actual_sales_amount
FROM v_target_breakdown vt
LEFT JOIN visits v
    ON  v.user_id          = vt.user_id
    AND v.business_line_id = vt.business_line_id
    AND EXTRACT(YEAR FROM COALESCE(v.submitted_at_local, v.submitted_at_utc)) = vt.year
    AND v.is_deleted = FALSE
WHERE vt.breakdown_level = 'business_line'
GROUP BY vt.id, vt.target_rep_id, vt.year, vt.breakdown_level,
    vt.user_id, vt.rep_name, vt.rep_region, vt.rep_role,
    vt.year_budget_amount, vt.year_budget_visits, vt.year_status,
    vt.customer_id, vt.customer_name, vt.customer_sector, vt.customer_region,
    vt.business_unit_id, vt.business_unit_name,
    vt.product_category_id, vt.product_category_name,
    vt.business_line_id, vt.business_line_name,
    vt.product_id, vt.article_number, vt.article_description,
    vt.target_amount, vt.target_visits, vt.productivity,
    vt.created_at, vt.updated_at;

CREATE OR REPLACE VIEW v_actual_vs_target_article AS
SELECT
    vt.id, vt.target_rep_id, vt.year, vt.breakdown_level,
    vt.user_id, vt.rep_name, vt.rep_region, vt.rep_role,
    vt.year_budget_amount, vt.year_budget_visits, vt.year_status,
    vt.customer_id, vt.customer_name, vt.customer_sector, vt.customer_region,
    vt.business_unit_id, vt.business_unit_name,
    vt.product_category_id, vt.product_category_name,
    vt.business_line_id, vt.business_line_name,
    vt.product_id, vt.article_number, vt.article_description,
    vt.target_amount, vt.target_visits, vt.productivity,
    vt.created_at, vt.updated_at,
    COUNT(DISTINCT v.visit_id)   AS actual_visits,
    CASE WHEN vt.target_visits > 0
         THEN ROUND(COUNT(DISTINCT v.visit_id)::NUMERIC / vt.target_visits * 100, 1)
         ELSE NULL END           AS visit_achievement_pct,
    NULL::NUMERIC                AS actual_sales_amount
FROM v_target_breakdown vt
LEFT JOIN visits v
    ON  v.user_id    = vt.user_id
    AND v.product_id = vt.product_id
    AND EXTRACT(YEAR FROM COALESCE(v.submitted_at_local, v.submitted_at_utc)) = vt.year
    AND v.is_deleted = FALSE
WHERE vt.breakdown_level = 'article'
GROUP BY vt.id, vt.target_rep_id, vt.year, vt.breakdown_level,
    vt.user_id, vt.rep_name, vt.rep_region, vt.rep_role,
    vt.year_budget_amount, vt.year_budget_visits, vt.year_status,
    vt.customer_id, vt.customer_name, vt.customer_sector, vt.customer_region,
    vt.business_unit_id, vt.business_unit_name,
    vt.product_category_id, vt.product_category_name,
    vt.business_line_id, vt.business_line_name,
    vt.product_id, vt.article_number, vt.article_description,
    vt.target_amount, vt.target_visits, vt.productivity,
    vt.created_at, vt.updated_at;
