table 'public shelf_movement_lines'
	isHidden
	lineageTag: c432aca3-617e-4eba-b9e5-927c66ac0622

	column line_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6202ac83-2e10-472b-ade2-f27f661fb473
		summarizeBy: sum
		sourceColumn: line_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column movement_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4db6ec41-1022-4b0d-abf3-fd9132d63896
		summarizeBy: none
		sourceColumn: movement_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d7e58656-dce6-4fb1-8fd3-e7c4d0b8ea85
		summarizeBy: sum
		sourceColumn: product_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qty_checked
		dataType: int64
		isHidden
		lineageTag: 5807b139-1510-4b8f-bae9-be8750e06a8d
		summarizeBy: sum
		sourceColumn: qty_checked

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'public shelf_movement_lines' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("dpg-d90llpn7f7vs73cot2fg-a.oregon-postgres.render.com", "ascenda_emc_db"),
				    public_shelf_movement_lines = Source{[Schema="public",Item="shelf_movement_lines"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(public_shelf_movement_lines,{{"line_id", Int64.Type}, {"movement_id", Int64.Type}, {"product_id", Int64.Type}, {"qty_checked", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

