table 'public objectives'
	isHidden
	lineageTag: 0abd6368-3701-4f67-9839-73d932b24684

	column 'Objective ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 23c20058-7952-433a-8297-6d9378f825c8
		summarizeBy: none
		sourceColumn: Objective ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Objective
		dataType: string
		isHidden
		lineageTag: cfd06ecd-35d8-48e6-8b5a-a3c61d91abbe
		summarizeBy: none
		sourceColumn: Objective

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 95d64c2b-fc30-4887-862f-61dfd73c5a49
		summarizeBy: none
		sourceColumn: is_active

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Objective Category'
		dataType: string
		isHidden
		lineageTag: 41330040-8668-4d70-864b-06b8bd48bef7
		summarizeBy: none
		sourceColumn: Objective Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'public objectives' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("dpg-d90llpn7f7vs73cot2fg-a.oregon-postgres.render.com", "ascenda_emc_db"),
				    public_objectives = Source{[Schema="public",Item="objectives"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(public_objectives,{{"objective_id", Int64.Type}, {"name", type text}, {"is_active", type logical}, {"category", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"name", "Objective"}, {"objective_id", "Objective ID"}, {"category", "Objective Category"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

