createOrReplace

	table 'VISITS vs POs_Lines'
		lineageTag: 1a871c47-c9da-4ddd-88f2-b1b6615a510f

		measure PRODUCTIVITY_LINES = 
				DIVIDE(
					SUM('VISITS vs POs_Lines'[POs]),
					SUM('VISITS vs POs_Lines'[VISITS])
				)
			lineageTag: e8299ae8-7836-43ef-a4a5-d38c2f2278e4

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column CATEGORY
			dataType: string
			lineageTag: 959ca678-6fd6-477b-aab8-b8312560a4b2
			summarizeBy: none
			sourceColumn: CATEGORY

			annotation SummarizationSetBy = Automatic

		column YEAR
			dataType: string
			lineageTag: f598f6f0-79b0-4908-bbca-cfd8af11dc1f
			summarizeBy: none
			sourceColumn: YEAR

			annotation SummarizationSetBy = Automatic

		column 'SALES REP (Original)'
			dataType: string
			lineageTag: 4c037898-3c87-4d8d-a359-cd66e5eebd41
			summarizeBy: none
			sourceColumn: SALES REP (Original)

			annotation SummarizationSetBy = Automatic

		column REGION
			dataType: string
			lineageTag: fe797096-2927-42aa-a647-c5a91b4f5804
			summarizeBy: none
			sourceColumn: REGION

			annotation SummarizationSetBy = Automatic

		column SECTOR
			dataType: string
			lineageTag: 1e7d16c5-0260-4bf5-a5bf-7707c1f6360e
			summarizeBy: none
			sourceColumn: SECTOR

			annotation SummarizationSetBy = Automatic

		column POs
			dataType: double
			lineageTag: 2dd39df2-39f1-44cb-89ff-8b808b6596a4
			summarizeBy: sum
			sourceColumn: POs

			changedProperty = DataType

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VISITS
			dataType: int64
			formatString: 0
			lineageTag: 7c3a366d-7c77-4dcb-971b-35a598786092
			summarizeBy: sum
			sourceColumn: VISITS

			changedProperty = DataType

			annotation SummarizationSetBy = Automatic

		column LINE
			dataType: string
			lineageTag: 9c337b31-333f-42ce-a1f2-4bc0eab29c50
			summarizeBy: none
			sourceColumn: LINE

			annotation SummarizationSetBy = Automatic

		partition 'VISITS vs POs_Lines' = m
			mode: import
			source = 
					let
						Source = Table.Combine({#"public visits_lines (Ammendable)", #"Category 12_Year 24-25-26_Lines_PT (Ammendable)"}),
						#"Filtered Rows" = Table.SelectRows(Source, each true),
						#"Renamed Columns" = Table.RenameColumns(
							#"Filtered Rows", {{"SALES REP.", "SALES REP (Original)"}, {"SUM of VISITS", "VISITS"}, {"POs Value", "POs"}}
						),
						#"Replaced Value" = Table.ReplaceValue(
							#"Renamed Columns", "12. AVANOS / ANES & ICU", "12. GASTACH / OT", Replacer.ReplaceText, {"CATEGORY"}
						),
						#"Replaced Value1" = Table.ReplaceValue(#"Replaced Value", 189, 283, Replacer.ReplaceValue, {"LINE"}),
						#"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1", 190, 284, Replacer.ReplaceValue, {"LINE"}),
						#"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2", 191, 285, Replacer.ReplaceValue, {"LINE"}),
						#"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3", 192, 286, Replacer.ReplaceValue, {"LINE"}),
						#"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4", 193, 287, Replacer.ReplaceValue, {"LINE"}),
						#"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5", 194, 288, Replacer.ReplaceValue, {"LINE"}),
						#"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6", 195, 295, Replacer.ReplaceValue, {"LINE"})
					in
						#"Replaced Value7"

		annotation PBI_NavigationStepName = Navigation

		annotation PBI_ResultType = Table
