createOrReplace

	table 'Category 12_Year 24-25-26_Lines_PT (Ammendable)'
		lineageTag: 0e28db83-2dbc-4744-ad15-b30159f3a93b

		column CATEGORY
			dataType: string
			lineageTag: 91ce63c9-5a6c-4ba5-83b3-e4aa1853239d
			summarizeBy: none
			sourceColumn: CATEGORY

			annotation SummarizationSetBy = Automatic

		column YEAR
			dataType: int64
			formatString: 0
			lineageTag: 949c732f-6b39-4283-833f-11831627e36f
			summarizeBy: sum
			sourceColumn: YEAR

			annotation SummarizationSetBy = Automatic

		column LINE
			dataType: string
			lineageTag: f37a31c7-f1da-464e-90e7-7442c28761ed
			summarizeBy: none
			sourceColumn: LINE

			annotation SummarizationSetBy = Automatic

		column 'SALES REP.'
			dataType: string
			lineageTag: 51f3f1ef-3bbf-45f2-a557-aa6db103cac0
			summarizeBy: none
			sourceColumn: SALES REP.

			annotation SummarizationSetBy = Automatic

		column REGION
			dataType: string
			lineageTag: 263b4cd3-0510-4ad1-b66b-2e92f2539c7e
			summarizeBy: none
			sourceColumn: REGION

			annotation SummarizationSetBy = Automatic

		column SECTOR
			dataType: string
			lineageTag: d1da302a-51b5-4e08-b68c-b3a520429806
			summarizeBy: none
			sourceColumn: SECTOR

			annotation SummarizationSetBy = Automatic

		column 'POs Value'
			dataType: double
			lineageTag: ee5778da-03e6-4320-91b0-26f6f3d12ccf
			summarizeBy: sum
			sourceColumn: POs Value

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'SUM of VISITS'
			dataType: string
			lineageTag: c9a6a944-6c54-4574-9823-a8a21ffb1aef
			summarizeBy: none
			sourceColumn: SUM of VISITS

			annotation SummarizationSetBy = Automatic

		partition 'Category 12_Year 24-25-26_Lines_PT (Ammendable)' = m
			mode: import
			source = 
					let
						Source = Excel.Workbook(
							File.Contents("C:\Users\Muhammad Sulaiman\Downloads\Ascenda_Masking Project\Ascenda Plus.xlsx"), null, true
						),
						#"Category 12_Year 24-25_PT (2)_Sheet" = Source{[Item = "Category 12_Year 24-25_PT (2)", Kind = "Sheet"]}[Data],
						#"Removed Top Rows" = Table.Skip(#"Category 12_Year 24-25_PT (2)_Sheet", 2),
						#"Promoted Headers1" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars = true]),
						#"Changed Type1" = Table.TransformColumnTypes(
							#"Promoted Headers1",
							{
								{"CATEGORY", type text},
								{"Year", Int64.Type},
								{"LINE", type text},
								{"SALES REP.", type text},
								{"REGION", type text},
								{"SECTOR", type text},
								{"Sum of TOTAL AMOUNT", type number}
							}
						),
						#"Replaced Value2" = Table.ReplaceValue(#"Changed Type1", "NUPCO (MOH)", "MOH", Replacer.ReplaceText, {"SECTOR"}),
						#"Replaced Value3" = Table.ReplaceValue(
							#"Replaced Value2", "NUPCO (GOVERNMENTAL)", "GOVERNMENTAL", Replacer.ReplaceText, {"SECTOR"}
						),
						#"Renamed Columns" = Table.RenameColumns(
							#"Replaced Value3", {{"Year", "YEAR"}, {"Sum of TOTAL AMOUNT", "POs Value"}}
						),
						#"Added Custom" = Table.AddColumn(#"Renamed Columns", "SUM of VISITS", each 0),
						#"Reordered Columns" = Table.ReorderColumns(
							#"Added Custom", {"CATEGORY", "YEAR", "LINE", "SALES REP.", "REGION", "SECTOR", "POs Value", "SUM of VISITS"}
						),
						#"Replaced Value4" = Table.ReplaceValue(
							#"Reordered Columns", "Akram Mahmoud Ahmed Al Saadi", "Zahra Al-Muaybid", Replacer.ReplaceText, {"SALES REP."}
						),
						#"Replaced Value5" = Table.ReplaceValue(
							#"Replaced Value4", "Mohamed Ibrahim Elkharsawy", "Mohamed El Kharsawy", Replacer.ReplaceText, {"SALES REP."}
						),
						#"Replaced Value6" = Table.ReplaceValue(
							#"Replaced Value5", "Wail Gawdat Ahmed", "Wail Ahmed", Replacer.ReplaceText, {"SALES REP."}
						),
						#"Replaced Value7" = Table.ReplaceValue(
							#"Replaced Value6", "Abdul Jawad Ahmed Abdul Haleem judah", "Abdul Jawad Ahmed", Replacer.ReplaceText, {
								"SALES REP."
							}
						),
						#"Replaced Value8" = Table.ReplaceValue(
							#"Replaced Value7", "Islam Mohamed El Serry", "Eslam Serry", Replacer.ReplaceText, {"SALES REP."}
						),
						#"Replaced Value" = Table.ReplaceValue(
							#"Replaced Value8", "283. AVANOS, Pain Mgmt RF Cannulae", "283", Replacer.ReplaceText, {"LINE"}
						),
						#"Replaced Value1" = Table.ReplaceValue(
							#"Replaced Value", "284. AVANOS, Pain Mgmt RF Equipment", "284", Replacer.ReplaceText, {"LINE"}
						),
						#"Replaced Value9" = Table.ReplaceValue(
							#"Replaced Value1", "285. AVANOS, Pain Mgmt RF Equipment Accessories", "285", Replacer.ReplaceText, {"LINE"}
						),
						#"Replaced Value10" = Table.ReplaceValue(
							#"Replaced Value9", "286. AVANOS, Pain Mgmt RF Probes", "286", Replacer.ReplaceText, {"LINE"}
						),
						#"Replaced Value11" = Table.ReplaceValue(
							#"Replaced Value10", "287. AVANOS, Pain Mgmt RF Water-Cooled Probes", "287", Replacer.ReplaceText, {"LINE"}
						)
					in
						#"Replaced Value11"

		annotation PBI_NavigationStepName = Navigation

		annotation PBI_ResultType = Table
