createOrReplace

	table 'public visits_customers (Ammendable)'
		lineageTag: b7a04f1c-a7c0-4449-a53e-c650c30277a5

		column CATEGORY
			dataType: string
			lineageTag: cfe3e685-3792-4707-8d7e-11352ad82bd3
			summarizeBy: none
			sourceColumn: CATEGORY

			annotation SummarizationSetBy = Automatic

		column CUSTOMER
			dataType: string
			lineageTag: 4d66d31f-629c-470e-abf5-3348d869f462
			summarizeBy: none
			sourceColumn: CUSTOMER

			annotation SummarizationSetBy = Automatic

		column 'SALES REP.'
			dataType: string
			lineageTag: 571af6de-c39a-4e3b-b4fa-c653a109d441
			summarizeBy: none
			sourceColumn: SALES REP.

			annotation SummarizationSetBy = Automatic

		column REGION
			dataType: string
			lineageTag: 7c57ba1b-19d7-4845-9fda-b172d4439a96
			summarizeBy: none
			sourceColumn: REGION

			annotation SummarizationSetBy = Automatic

		column SECTOR
			dataType: string
			lineageTag: 9c86c876-e1fb-4887-9490-6be9f9554e24
			summarizeBy: none
			sourceColumn: SECTOR

			annotation SummarizationSetBy = Automatic

		column 'POs Value'
			dataType: string
			lineageTag: 7e39deff-298e-4529-8532-e2f9a0ae6ef1
			summarizeBy: none
			sourceColumn: POs Value

			annotation SummarizationSetBy = Automatic

		column YEAR
			dataType: string
			lineageTag: e51ddbec-f09a-43a8-b1b1-253ae3f75ff5
			summarizeBy: none
			sourceColumn: YEAR

			annotation SummarizationSetBy = Automatic

		column 'SUM of VISITS'
			dataType: double
			lineageTag: ccd43c23-b8f7-499c-9655-b438be749d51
			summarizeBy: sum
			sourceColumn: SUM of VISITS

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		partition 'public visits_customers (Ammendable)' = m
			mode: import
			source = 
					let
						Source = #"public visits",
						#"Added Custom" = Table.AddColumn(Source, "Visit Count", each 1),
						#"Grouped Rows" = Table.Group(
							#"Added Custom",
							{"business_line_id", "customer_id", "user_id", "yearx"},
							{{"SUM of VISITS", each List.Sum([Visit Count]), type number}}
						),
						#"Merged Queries" = Table.NestedJoin(
							#"Grouped Rows",
							{"business_line_id"},
							#"public business_lines",
							{"Business Line ID"},
							"public business_lines",
							JoinKind.LeftOuter
						),
						#"Expanded public business_lines" = Table.ExpandTableColumn(
							#"Merged Queries", "public business_lines", {"Product Category"}, {"public business_lines.Product Category"}
						),
						#"Merged Queries1" = Table.NestedJoin(
							#"Expanded public business_lines",
							{"customer_id"},
							#"public customers",
							{"Customer ID"},
							"public customers",
							JoinKind.LeftOuter
						),
						#"Expanded public customers" = Table.ExpandTableColumn(
							#"Merged Queries1",
							"public customers",
							{"Customer Name", "Sector", "Region"},
							{"public customers.Customer Name", "public customers.Sector", "public customers.Region"}
						),
						#"Merged Queries2" = Table.NestedJoin(
							#"Expanded public customers", {"user_id"}, #"public users", {"user_id"}, "public users", JoinKind.LeftOuter
						),
						#"Expanded public users" = Table.ExpandTableColumn(
							#"Merged Queries2", "public users", {"Frontline Name"}, {"public users.Frontline Name"}
						),
						#"Removed Other Columns" = Table.SelectColumns(
							#"Expanded public users",
							{
								"yearx",
								"SUM of VISITS",
								"public business_lines.Product Category",
								"public customers.Customer Name",
								"public customers.Sector",
								"public customers.Region",
								"public users.Frontline Name"
							}
						),
						#"Reordered Columns" = Table.ReorderColumns(
							#"Removed Other Columns",
							{
								"public business_lines.Product Category",
								"yearx",
								"public customers.Customer Name",
								"public users.Frontline Name",
								"public customers.Region",
								"public customers.Sector",
								"SUM of VISITS"
							}
						),
						#"Added Custom1" = Table.AddColumn(#"Reordered Columns", "POs Value", each 0),
						#"Reordered Columns1" = Table.ReorderColumns(
							#"Added Custom1",
							{
								"public business_lines.Product Category",
								"yearx",
								"public customers.Customer Name",
								"public users.Frontline Name",
								"public customers.Region",
								"public customers.Sector",
								"POs Value",
								"SUM of VISITS"
							}
						),
						#"Renamed Columns" = Table.RenameColumns(
							#"Reordered Columns1",
							{
								{"public business_lines.Product Category", "CATEGORY"},
								{"public customers.Customer Name", "CUSTOMER"},
								{"public users.Frontline Name", "SALES REP."},
								{"public customers.Region", "REGION"},
								{"public customers.Sector", "SECTOR"},
								{"yearx", "YEAR"}
							}
						),
						#"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([CATEGORY] = "12. GASTACH / OT") and ([YEAR] > 2023)),
						#"Replaced Value" = Table.ReplaceValue(
							#"Filtered Rows", "SALAH ZULFIKAR", "AHMAD RAMZY", Replacer.ReplaceText, {"SALES REP."}
						)
					in
						#"Replaced Value"

		annotation PBI_NavigationStepName = Navigation

		annotation PBI_ResultType = Table
