table 'Category 12_Year 24-25-26_Customers_PT (Ammendable)'
	isHidden
	lineageTag: 38458b9b-bb62-4464-b899-2397c32c7842

	column CATEGORY
		dataType: string
		isHidden
		lineageTag: 066779f0-4985-4a6b-8972-d00453656554
		summarizeBy: none
		sourceColumn: CATEGORY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YEAR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 864d1b3e-64c4-4340-ac53-e88f1c9d7f6a
		summarizeBy: sum
		sourceColumn: YEAR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'SALES REP.'
		dataType: string
		isHidden
		lineageTag: 14103437-b9c4-46ef-b4aa-717e4146dd99
		summarizeBy: none
		sourceColumn: SALES REP.

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column REGION
		dataType: string
		isHidden
		lineageTag: 801af8b3-9e2d-4868-b3c5-57f374e84186
		summarizeBy: none
		sourceColumn: REGION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SECTOR
		dataType: string
		isHidden
		lineageTag: f6e7e00e-8f49-4db0-b753-bfdc99fe709e
		summarizeBy: none
		sourceColumn: SECTOR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'POs Value'
		dataType: double
		isHidden
		lineageTag: 85107b6b-f557-44b1-9633-f70a9769c474
		summarizeBy: sum
		sourceColumn: POs Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SUM of VISITS'
		dataType: string
		isHidden
		lineageTag: 1ef2b360-e8ba-436d-87ce-987b4f3f9976
		summarizeBy: none
		sourceColumn: SUM of VISITS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CUSTOMER
		dataType: string
		isHidden
		lineageTag: 628d3b75-c599-4a51-82c5-0e270bc84d77
		summarizeBy: none
		sourceColumn: CUSTOMER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Category 12_Year 24-25-26_Customers_PT (Ammendable)' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Muhammad Sulaiman\Downloads\Ascenda_Masking Project\Ascenda Plus.xlsx"), null, true),
				    #"Category 12_Year 24-25_PT_Sheet" = Source{[Item="Category 12_Year 24-25_PT",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(#"Category 12_Year 24-25_PT_Sheet",2),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"CATEGORY", type text}, {"Year", Int64.Type}, {"CUSTOMER", type text}, {"SALES REP.", type text}, {"REGION", type text}, {"SECTOR", type text}, {"Sum of TOTAL AMOUNT", type number}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","Security Forces Hospital Program – Riyadh (NUPCO)","Security Forces Hospital Program - Riyadh (NUPCO)",Replacer.ReplaceText,{"CUSTOMER"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Qassim Health Cluster","Health Cluster - Qassim",Replacer.ReplaceText,{"CUSTOMER"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","NUPCO (MOH)","MOH",Replacer.ReplaceText,{"SECTOR"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","NUPCO (GOVERNMENTAL)","GOVERNMENTAL",Replacer.ReplaceText,{"SECTOR"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value3",{{"Year", "YEAR"}, {"Sum of TOTAL AMOUNT", "POs Value"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "SUM of VISITS", each 0),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "CUSTOMER_ADJ", each if [CUSTOMER] <> null then
				    Text.Replace([CUSTOMER], " (NUPCO)", "")
				else
				    null),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom1",{"CUSTOMER"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"CATEGORY", "YEAR", "CUSTOMER_ADJ", "SALES REP.", "REGION", "SECTOR", "POs Value", "SUM of VISITS"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"CUSTOMER_ADJ", "CUSTOMER"}}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Renamed Columns1","Akram Mahmoud Ahmed Al Saadi","Zahra Al-Muaybid",Replacer.ReplaceText,{"SALES REP."}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Mohamed Ibrahim Elkharsawy","Mohamed El Kharsawy",Replacer.ReplaceText,{"SALES REP."}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Wail Gawdat Ahmed","Wail Ahmed",Replacer.ReplaceText,{"SALES REP."}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Abdul Jawad Ahmed Abdul Haleem judah","Abdul Jawad Ahmed",Replacer.ReplaceText,{"SALES REP."}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Islam Mohamed El Serry","Eslam Serry",Replacer.ReplaceText,{"SALES REP."})
				in
				    #"Replaced Value8"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

