table 'public items'
	isHidden
	lineageTag: 293433fb-ff94-41e7-9407-1c5e1b0aef51

	column 'Product ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 01cd9cee-45ce-49e1-b6fc-3633e0eb23d1
		summarizeBy: none
		sourceColumn: Product ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Article #'
		dataType: string
		isHidden
		lineageTag: 602434cc-63c8-460a-9048-b632cb929400
		summarizeBy: none
		sourceColumn: Article #

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Description'
		dataType: string
		isHidden
		lineageTag: 942e993b-a4a4-4f79-876e-b1882cc1cde2
		summarizeBy: none
		sourceColumn: Item Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Business Line ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ff88f96e-65a9-4a52-af92-eba11dee2526
		summarizeBy: none
		sourceColumn: Business Line ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4da63681-7f98-4069-9fa5-56329cd62f49
		summarizeBy: none
		sourceColumn: is_active

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'public items' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Muhammad Sulaiman\Downloads\Ascenda_Masking Project\ascenda_backup.xlsx"), null, true),
				    public_items = Source{[Item="items",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(public_items, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", Int64.Type}, {"article_number", type text}, {"description", type text}, {"business_line_id", Int64.Type}, {"is_active", type logical}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"product_id", "Product ID"}, {"article_number", "Article #"}, {"description", "Item Description"}, {"business_line_id", "Business Line ID"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

