table 'public business_lines'
	isHidden
	lineageTag: d838eda1-32b9-45c6-a7bd-72b1ba832924

	column 'Business Line ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 464a6cf1-e03f-4748-910b-8c768caedef3
		summarizeBy: none
		sourceColumn: Business Line ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Business Unit ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2d1949bf-40c4-43b4-8f45-9a237fd220aa
		summarizeBy: none
		sourceColumn: Business Unit ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Business Line'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e412d7b7-6244-4a44-b4b7-fea0999d0fb8
		summarizeBy: sum
		sourceColumn: Business Line

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Supplier
		dataType: string
		isHidden
		lineageTag: 55907542-2e6e-4a35-8c04-6f535670c9c6
		summarizeBy: none
		sourceColumn: Supplier

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		isHidden
		lineageTag: 84108213-2966-4ab6-84ae-4e3cefa0c1b8
		summarizeBy: none
		sourceColumn: Product Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Group'
		dataType: string
		isHidden
		lineageTag: a5806767-680b-43b4-b82a-999324004278
		summarizeBy: none
		sourceColumn: Product Group

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c6cd3367-5879-4e10-88fb-8a399ca8e23f
		summarizeBy: none
		sourceColumn: is_active

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Business Line Mask' = "Business Line " & 'public business_lines'[Business Line ID]
		isHidden
		lineageTag: 38276ac0-8853-4424-8dc2-09f0078c5925
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Category Mask' = "Product Category " & LEFT('public business_lines'[Product Category],2)
		isHidden
		lineageTag: aa53704c-0fe4-46c3-a779-fa855bdfdf1c
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'public business_lines' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Muhammad Sulaiman\Downloads\Ascenda_Masking Project\ascenda_backup.xlsx"), null, true),
				    public_business_lines = Source{[Item="business_lines",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(public_business_lines, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"business_line_id", Int64.Type}, {"business_unit_id", Int64.Type}, {"name", Int64.Type}, {"supplier", type text}, {"category", type text}, {"product_group", type text}, {"is_active", type logical}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type", {{"name", 0}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Errors",{{"name", "Business Line"}, {"business_line_id", "Business Line ID"}, {"business_unit_id", "Business Unit ID"}, {"supplier", "Supplier"}, {"category", "Product Category"}, {"product_group", "Product Group"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

