table 'public customers'
	isHidden
	lineageTag: 549d3d2a-e382-4d84-9cb2-e5348a771c02

	column 'Customer ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 03a7846a-8104-4669-83f5-c1b032c24562
		summarizeBy: none
		sourceColumn: Customer ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		isHidden
		lineageTag: f23003a0-f27f-4b83-b225-8344cd64dd2e
		summarizeBy: none
		sourceColumn: Customer Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sector
		dataType: string
		isHidden
		lineageTag: 5ca4f6f6-aa9f-477d-80f8-9ea325c1454f
		summarizeBy: none
		sourceColumn: Sector

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		isHidden
		lineageTag: ab74ba39-eba3-4a97-8b9d-b1326448f890
		summarizeBy: none
		sourceColumn: Region

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		isHidden
		lineageTag: dee1cb46-3c3c-4f26-8bf5-1d8a1ae9c9b3
		summarizeBy: none
		sourceColumn: City

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 363efa1e-0c7f-4281-8aad-422cd12ceb45
		summarizeBy: none
		sourceColumn: is_active

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		isHidden
		lineageTag: 4bc9a812-01a5-47db-95f5-5725272555d4
		summarizeBy: none
		sourceColumn: latitude

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		isHidden
		lineageTag: 89b9d5e9-c711-42b1-9872-97602669a422
		summarizeBy: none
		sourceColumn: longitude

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column party_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 868c6342-e670-4c39-9e3d-99c3219fb2f8
		summarizeBy: none
		sourceColumn: party_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column account_id
		dataType: string
		isHidden
		lineageTag: 38e51b1a-d5d5-489c-87b9-687554ee414e
		summarizeBy: none
		sourceColumn: account_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Customer Name Mask' = "Customer " & 'public customers'[Customer ID]
		isHidden
		lineageTag: e091fc2a-ebe0-458a-b72b-37d5f582e55b
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'public customers' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Muhammad Sulaiman\Downloads\Ascenda_Masking Project\ascenda_backup.xlsx"), null, true),
				    public_customers = Source{[Item="customers",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(public_customers, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"account_name", type text}, {"sector", type text}, {"region", type text}, {"city", type text}, {"is_active", type logical}, {"latitude", type number}, {"longitude", type number}, {"party_id", Int64.Type}, {"account_id", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"customer_id", "Customer ID"}, {"account_name", "Customer Name"}, {"sector", "Sector"}, {"region", "Region"}, {"city", "City"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

